// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.32.0
// source: driver.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { UserId } from "./common";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "lastmile.driver";

export interface RegisterDriverRequest {
  userId: string;
  vehicleNo: string;
  capacity: number;
  model: string;
  color: string;
}

export interface DriverProfile {
  driverId: string;
  userId: string;
  vehicleNo: string;
  capacity: number;
  routes: RoutePlan[];
  model: string;
  color: string;
}

export interface RoutePlan {
  routeId: string;
  driverId: string;
  stops: RouteStop[];
  finalAreaId: string;
  createdAt: Date | undefined;
}

export interface RouteStop {
  sequence: number;
  areaId: string;
  isStation: boolean;
  arrivalOffsetMinutes: number;
}

export interface RegisterRouteRequest {
  driverId: string;
  stops: RouteStop[];
}

export interface UpdateRouteRequest {
  driverId: string;
  routeId: string;
  stops: RouteStop[];
}

export interface UpdatePickupRequest {
  driverId: string;
  routeId: string;
  pickingUp: boolean;
}

export interface Ack {
  ok: boolean;
  msg: string;
}

export interface DriverId {
  id: string;
}

function createBaseRegisterDriverRequest(): RegisterDriverRequest {
  return { userId: "", vehicleNo: "", capacity: 0, model: "", color: "" };
}

export const RegisterDriverRequest: MessageFns<RegisterDriverRequest> = {
  encode(message: RegisterDriverRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.vehicleNo !== "") {
      writer.uint32(18).string(message.vehicleNo);
    }
    if (message.capacity !== 0) {
      writer.uint32(24).int32(message.capacity);
    }
    if (message.model !== "") {
      writer.uint32(34).string(message.model);
    }
    if (message.color !== "") {
      writer.uint32(42).string(message.color);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterDriverRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterDriverRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.vehicleNo = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.capacity = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.model = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.color = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterDriverRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      vehicleNo: isSet(object.vehicleNo) ? globalThis.String(object.vehicleNo) : "",
      capacity: isSet(object.capacity) ? globalThis.Number(object.capacity) : 0,
      model: isSet(object.model) ? globalThis.String(object.model) : "",
      color: isSet(object.color) ? globalThis.String(object.color) : "",
    };
  },

  toJSON(message: RegisterDriverRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.vehicleNo !== "") {
      obj.vehicleNo = message.vehicleNo;
    }
    if (message.capacity !== 0) {
      obj.capacity = Math.round(message.capacity);
    }
    if (message.model !== "") {
      obj.model = message.model;
    }
    if (message.color !== "") {
      obj.color = message.color;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RegisterDriverRequest>, I>>(base?: I): RegisterDriverRequest {
    return RegisterDriverRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterDriverRequest>, I>>(object: I): RegisterDriverRequest {
    const message = createBaseRegisterDriverRequest();
    message.userId = object.userId ?? "";
    message.vehicleNo = object.vehicleNo ?? "";
    message.capacity = object.capacity ?? 0;
    message.model = object.model ?? "";
    message.color = object.color ?? "";
    return message;
  },
};

function createBaseDriverProfile(): DriverProfile {
  return { driverId: "", userId: "", vehicleNo: "", capacity: 0, routes: [], model: "", color: "" };
}

export const DriverProfile: MessageFns<DriverProfile> = {
  encode(message: DriverProfile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.driverId !== "") {
      writer.uint32(10).string(message.driverId);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.vehicleNo !== "") {
      writer.uint32(26).string(message.vehicleNo);
    }
    if (message.capacity !== 0) {
      writer.uint32(32).int32(message.capacity);
    }
    for (const v of message.routes) {
      RoutePlan.encode(v!, writer.uint32(42).fork()).join();
    }
    if (message.model !== "") {
      writer.uint32(50).string(message.model);
    }
    if (message.color !== "") {
      writer.uint32(58).string(message.color);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DriverProfile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDriverProfile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.driverId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.vehicleNo = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.capacity = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.routes.push(RoutePlan.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.model = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.color = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DriverProfile {
    return {
      driverId: isSet(object.driverId) ? globalThis.String(object.driverId) : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      vehicleNo: isSet(object.vehicleNo) ? globalThis.String(object.vehicleNo) : "",
      capacity: isSet(object.capacity) ? globalThis.Number(object.capacity) : 0,
      routes: globalThis.Array.isArray(object?.routes) ? object.routes.map((e: any) => RoutePlan.fromJSON(e)) : [],
      model: isSet(object.model) ? globalThis.String(object.model) : "",
      color: isSet(object.color) ? globalThis.String(object.color) : "",
    };
  },

  toJSON(message: DriverProfile): unknown {
    const obj: any = {};
    if (message.driverId !== "") {
      obj.driverId = message.driverId;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.vehicleNo !== "") {
      obj.vehicleNo = message.vehicleNo;
    }
    if (message.capacity !== 0) {
      obj.capacity = Math.round(message.capacity);
    }
    if (message.routes?.length) {
      obj.routes = message.routes.map((e) => RoutePlan.toJSON(e));
    }
    if (message.model !== "") {
      obj.model = message.model;
    }
    if (message.color !== "") {
      obj.color = message.color;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DriverProfile>, I>>(base?: I): DriverProfile {
    return DriverProfile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DriverProfile>, I>>(object: I): DriverProfile {
    const message = createBaseDriverProfile();
    message.driverId = object.driverId ?? "";
    message.userId = object.userId ?? "";
    message.vehicleNo = object.vehicleNo ?? "";
    message.capacity = object.capacity ?? 0;
    message.routes = object.routes?.map((e) => RoutePlan.fromPartial(e)) || [];
    message.model = object.model ?? "";
    message.color = object.color ?? "";
    return message;
  },
};

function createBaseRoutePlan(): RoutePlan {
  return { routeId: "", driverId: "", stops: [], finalAreaId: "", createdAt: undefined };
}

export const RoutePlan: MessageFns<RoutePlan> = {
  encode(message: RoutePlan, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.routeId !== "") {
      writer.uint32(10).string(message.routeId);
    }
    if (message.driverId !== "") {
      writer.uint32(18).string(message.driverId);
    }
    for (const v of message.stops) {
      RouteStop.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.finalAreaId !== "") {
      writer.uint32(34).string(message.finalAreaId);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoutePlan {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoutePlan();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.routeId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.driverId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.stops.push(RouteStop.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.finalAreaId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RoutePlan {
    return {
      routeId: isSet(object.routeId) ? globalThis.String(object.routeId) : "",
      driverId: isSet(object.driverId) ? globalThis.String(object.driverId) : "",
      stops: globalThis.Array.isArray(object?.stops) ? object.stops.map((e: any) => RouteStop.fromJSON(e)) : [],
      finalAreaId: isSet(object.finalAreaId) ? globalThis.String(object.finalAreaId) : "",
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
    };
  },

  toJSON(message: RoutePlan): unknown {
    const obj: any = {};
    if (message.routeId !== "") {
      obj.routeId = message.routeId;
    }
    if (message.driverId !== "") {
      obj.driverId = message.driverId;
    }
    if (message.stops?.length) {
      obj.stops = message.stops.map((e) => RouteStop.toJSON(e));
    }
    if (message.finalAreaId !== "") {
      obj.finalAreaId = message.finalAreaId;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RoutePlan>, I>>(base?: I): RoutePlan {
    return RoutePlan.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RoutePlan>, I>>(object: I): RoutePlan {
    const message = createBaseRoutePlan();
    message.routeId = object.routeId ?? "";
    message.driverId = object.driverId ?? "";
    message.stops = object.stops?.map((e) => RouteStop.fromPartial(e)) || [];
    message.finalAreaId = object.finalAreaId ?? "";
    message.createdAt = object.createdAt ?? undefined;
    return message;
  },
};

function createBaseRouteStop(): RouteStop {
  return { sequence: 0, areaId: "", isStation: false, arrivalOffsetMinutes: 0 };
}

export const RouteStop: MessageFns<RouteStop> = {
  encode(message: RouteStop, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sequence !== 0) {
      writer.uint32(8).int32(message.sequence);
    }
    if (message.areaId !== "") {
      writer.uint32(18).string(message.areaId);
    }
    if (message.isStation !== false) {
      writer.uint32(24).bool(message.isStation);
    }
    if (message.arrivalOffsetMinutes !== 0) {
      writer.uint32(32).int32(message.arrivalOffsetMinutes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RouteStop {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRouteStop();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.sequence = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.areaId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isStation = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.arrivalOffsetMinutes = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RouteStop {
    return {
      sequence: isSet(object.sequence) ? globalThis.Number(object.sequence) : 0,
      areaId: isSet(object.areaId) ? globalThis.String(object.areaId) : "",
      isStation: isSet(object.isStation) ? globalThis.Boolean(object.isStation) : false,
      arrivalOffsetMinutes: isSet(object.arrivalOffsetMinutes) ? globalThis.Number(object.arrivalOffsetMinutes) : 0,
    };
  },

  toJSON(message: RouteStop): unknown {
    const obj: any = {};
    if (message.sequence !== 0) {
      obj.sequence = Math.round(message.sequence);
    }
    if (message.areaId !== "") {
      obj.areaId = message.areaId;
    }
    if (message.isStation !== false) {
      obj.isStation = message.isStation;
    }
    if (message.arrivalOffsetMinutes !== 0) {
      obj.arrivalOffsetMinutes = Math.round(message.arrivalOffsetMinutes);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RouteStop>, I>>(base?: I): RouteStop {
    return RouteStop.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RouteStop>, I>>(object: I): RouteStop {
    const message = createBaseRouteStop();
    message.sequence = object.sequence ?? 0;
    message.areaId = object.areaId ?? "";
    message.isStation = object.isStation ?? false;
    message.arrivalOffsetMinutes = object.arrivalOffsetMinutes ?? 0;
    return message;
  },
};

function createBaseRegisterRouteRequest(): RegisterRouteRequest {
  return { driverId: "", stops: [] };
}

export const RegisterRouteRequest: MessageFns<RegisterRouteRequest> = {
  encode(message: RegisterRouteRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.driverId !== "") {
      writer.uint32(10).string(message.driverId);
    }
    for (const v of message.stops) {
      RouteStop.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterRouteRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterRouteRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.driverId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.stops.push(RouteStop.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterRouteRequest {
    return {
      driverId: isSet(object.driverId) ? globalThis.String(object.driverId) : "",
      stops: globalThis.Array.isArray(object?.stops) ? object.stops.map((e: any) => RouteStop.fromJSON(e)) : [],
    };
  },

  toJSON(message: RegisterRouteRequest): unknown {
    const obj: any = {};
    if (message.driverId !== "") {
      obj.driverId = message.driverId;
    }
    if (message.stops?.length) {
      obj.stops = message.stops.map((e) => RouteStop.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RegisterRouteRequest>, I>>(base?: I): RegisterRouteRequest {
    return RegisterRouteRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterRouteRequest>, I>>(object: I): RegisterRouteRequest {
    const message = createBaseRegisterRouteRequest();
    message.driverId = object.driverId ?? "";
    message.stops = object.stops?.map((e) => RouteStop.fromPartial(e)) || [];
    return message;
  },
};

function createBaseUpdateRouteRequest(): UpdateRouteRequest {
  return { driverId: "", routeId: "", stops: [] };
}

export const UpdateRouteRequest: MessageFns<UpdateRouteRequest> = {
  encode(message: UpdateRouteRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.driverId !== "") {
      writer.uint32(10).string(message.driverId);
    }
    if (message.routeId !== "") {
      writer.uint32(18).string(message.routeId);
    }
    for (const v of message.stops) {
      RouteStop.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateRouteRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateRouteRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.driverId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.routeId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.stops.push(RouteStop.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateRouteRequest {
    return {
      driverId: isSet(object.driverId) ? globalThis.String(object.driverId) : "",
      routeId: isSet(object.routeId) ? globalThis.String(object.routeId) : "",
      stops: globalThis.Array.isArray(object?.stops) ? object.stops.map((e: any) => RouteStop.fromJSON(e)) : [],
    };
  },

  toJSON(message: UpdateRouteRequest): unknown {
    const obj: any = {};
    if (message.driverId !== "") {
      obj.driverId = message.driverId;
    }
    if (message.routeId !== "") {
      obj.routeId = message.routeId;
    }
    if (message.stops?.length) {
      obj.stops = message.stops.map((e) => RouteStop.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateRouteRequest>, I>>(base?: I): UpdateRouteRequest {
    return UpdateRouteRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateRouteRequest>, I>>(object: I): UpdateRouteRequest {
    const message = createBaseUpdateRouteRequest();
    message.driverId = object.driverId ?? "";
    message.routeId = object.routeId ?? "";
    message.stops = object.stops?.map((e) => RouteStop.fromPartial(e)) || [];
    return message;
  },
};

function createBaseUpdatePickupRequest(): UpdatePickupRequest {
  return { driverId: "", routeId: "", pickingUp: false };
}

export const UpdatePickupRequest: MessageFns<UpdatePickupRequest> = {
  encode(message: UpdatePickupRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.driverId !== "") {
      writer.uint32(10).string(message.driverId);
    }
    if (message.routeId !== "") {
      writer.uint32(18).string(message.routeId);
    }
    if (message.pickingUp !== false) {
      writer.uint32(24).bool(message.pickingUp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdatePickupRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdatePickupRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.driverId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.routeId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.pickingUp = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdatePickupRequest {
    return {
      driverId: isSet(object.driverId) ? globalThis.String(object.driverId) : "",
      routeId: isSet(object.routeId) ? globalThis.String(object.routeId) : "",
      pickingUp: isSet(object.pickingUp) ? globalThis.Boolean(object.pickingUp) : false,
    };
  },

  toJSON(message: UpdatePickupRequest): unknown {
    const obj: any = {};
    if (message.driverId !== "") {
      obj.driverId = message.driverId;
    }
    if (message.routeId !== "") {
      obj.routeId = message.routeId;
    }
    if (message.pickingUp !== false) {
      obj.pickingUp = message.pickingUp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdatePickupRequest>, I>>(base?: I): UpdatePickupRequest {
    return UpdatePickupRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdatePickupRequest>, I>>(object: I): UpdatePickupRequest {
    const message = createBaseUpdatePickupRequest();
    message.driverId = object.driverId ?? "";
    message.routeId = object.routeId ?? "";
    message.pickingUp = object.pickingUp ?? false;
    return message;
  },
};

function createBaseAck(): Ack {
  return { ok: false, msg: "" };
}

export const Ack: MessageFns<Ack> = {
  encode(message: Ack, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ok !== false) {
      writer.uint32(8).bool(message.ok);
    }
    if (message.msg !== "") {
      writer.uint32(18).string(message.msg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Ack {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAck();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ok = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.msg = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Ack {
    return {
      ok: isSet(object.ok) ? globalThis.Boolean(object.ok) : false,
      msg: isSet(object.msg) ? globalThis.String(object.msg) : "",
    };
  },

  toJSON(message: Ack): unknown {
    const obj: any = {};
    if (message.ok !== false) {
      obj.ok = message.ok;
    }
    if (message.msg !== "") {
      obj.msg = message.msg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Ack>, I>>(base?: I): Ack {
    return Ack.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Ack>, I>>(object: I): Ack {
    const message = createBaseAck();
    message.ok = object.ok ?? false;
    message.msg = object.msg ?? "";
    return message;
  },
};

function createBaseDriverId(): DriverId {
  return { id: "" };
}

export const DriverId: MessageFns<DriverId> = {
  encode(message: DriverId, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DriverId {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDriverId();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DriverId {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: DriverId): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DriverId>, I>>(base?: I): DriverId {
    return DriverId.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DriverId>, I>>(object: I): DriverId {
    const message = createBaseDriverId();
    message.id = object.id ?? "";
    return message;
  },
};

export interface DriverService {
  RegisterDriver(request: RegisterDriverRequest): Promise<DriverProfile>;
  RegisterRoute(request: RegisterRouteRequest): Promise<RoutePlan>;
  UpdateRoute(request: UpdateRouteRequest): Promise<RoutePlan>;
  UpdatePickupStatus(request: UpdatePickupRequest): Promise<Ack>;
  GetDriver(request: DriverId): Promise<DriverProfile>;
  GetDriverByUserId(request: UserId): Promise<DriverProfile>;
}

export const DriverServiceServiceName = "lastmile.driver.DriverService";
export class DriverServiceClientImpl implements DriverService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || DriverServiceServiceName;
    this.rpc = rpc;
    this.RegisterDriver = this.RegisterDriver.bind(this);
    this.RegisterRoute = this.RegisterRoute.bind(this);
    this.UpdateRoute = this.UpdateRoute.bind(this);
    this.UpdatePickupStatus = this.UpdatePickupStatus.bind(this);
    this.GetDriver = this.GetDriver.bind(this);
    this.GetDriverByUserId = this.GetDriverByUserId.bind(this);
  }
  RegisterDriver(request: RegisterDriverRequest): Promise<DriverProfile> {
    const data = RegisterDriverRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "RegisterDriver", data);
    return promise.then((data) => DriverProfile.decode(new BinaryReader(data)));
  }

  RegisterRoute(request: RegisterRouteRequest): Promise<RoutePlan> {
    const data = RegisterRouteRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "RegisterRoute", data);
    return promise.then((data) => RoutePlan.decode(new BinaryReader(data)));
  }

  UpdateRoute(request: UpdateRouteRequest): Promise<RoutePlan> {
    const data = UpdateRouteRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateRoute", data);
    return promise.then((data) => RoutePlan.decode(new BinaryReader(data)));
  }

  UpdatePickupStatus(request: UpdatePickupRequest): Promise<Ack> {
    const data = UpdatePickupRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdatePickupStatus", data);
    return promise.then((data) => Ack.decode(new BinaryReader(data)));
  }

  GetDriver(request: DriverId): Promise<DriverProfile> {
    const data = DriverId.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetDriver", data);
    return promise.then((data) => DriverProfile.decode(new BinaryReader(data)));
  }

  GetDriverByUserId(request: UserId): Promise<DriverProfile> {
    const data = UserId.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetDriverByUserId", data);
    return promise.then((data) => DriverProfile.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
