// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.32.0
// source: location.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Observable } from "rxjs";
import { map } from "rxjs/operators";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "lastmile.location";

export interface DriverTelemetry {
  driverId: string;
  routeId: string;
  currentAreaId: string;
  occupancy: number;
  ts: Date | undefined;
}

export interface DriverSnapshot {
  driverId: string;
  routeId: string;
  currentAreaId: string;
  occupancy: number;
  ts: Date | undefined;
}

export interface DriverEtaRequest {
  driverId: string;
  stationAreaId: string;
}

export interface DriverEta {
  driverId: string;
  stationAreaId: string;
  reachable: boolean;
  etaMinutes: number;
}

export interface DriverId {
  id: string;
}

export interface Ack {
  ok: boolean;
  msg: string;
}

function createBaseDriverTelemetry(): DriverTelemetry {
  return { driverId: "", routeId: "", currentAreaId: "", occupancy: 0, ts: undefined };
}

export const DriverTelemetry: MessageFns<DriverTelemetry> = {
  encode(message: DriverTelemetry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.driverId !== "") {
      writer.uint32(10).string(message.driverId);
    }
    if (message.routeId !== "") {
      writer.uint32(18).string(message.routeId);
    }
    if (message.currentAreaId !== "") {
      writer.uint32(26).string(message.currentAreaId);
    }
    if (message.occupancy !== 0) {
      writer.uint32(32).int32(message.occupancy);
    }
    if (message.ts !== undefined) {
      Timestamp.encode(toTimestamp(message.ts), writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DriverTelemetry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDriverTelemetry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.driverId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.routeId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.currentAreaId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.occupancy = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.ts = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DriverTelemetry {
    return {
      driverId: isSet(object.driverId) ? globalThis.String(object.driverId) : "",
      routeId: isSet(object.routeId) ? globalThis.String(object.routeId) : "",
      currentAreaId: isSet(object.currentAreaId) ? globalThis.String(object.currentAreaId) : "",
      occupancy: isSet(object.occupancy) ? globalThis.Number(object.occupancy) : 0,
      ts: isSet(object.ts) ? fromJsonTimestamp(object.ts) : undefined,
    };
  },

  toJSON(message: DriverTelemetry): unknown {
    const obj: any = {};
    if (message.driverId !== "") {
      obj.driverId = message.driverId;
    }
    if (message.routeId !== "") {
      obj.routeId = message.routeId;
    }
    if (message.currentAreaId !== "") {
      obj.currentAreaId = message.currentAreaId;
    }
    if (message.occupancy !== 0) {
      obj.occupancy = Math.round(message.occupancy);
    }
    if (message.ts !== undefined) {
      obj.ts = message.ts.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DriverTelemetry>, I>>(base?: I): DriverTelemetry {
    return DriverTelemetry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DriverTelemetry>, I>>(object: I): DriverTelemetry {
    const message = createBaseDriverTelemetry();
    message.driverId = object.driverId ?? "";
    message.routeId = object.routeId ?? "";
    message.currentAreaId = object.currentAreaId ?? "";
    message.occupancy = object.occupancy ?? 0;
    message.ts = object.ts ?? undefined;
    return message;
  },
};

function createBaseDriverSnapshot(): DriverSnapshot {
  return { driverId: "", routeId: "", currentAreaId: "", occupancy: 0, ts: undefined };
}

export const DriverSnapshot: MessageFns<DriverSnapshot> = {
  encode(message: DriverSnapshot, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.driverId !== "") {
      writer.uint32(10).string(message.driverId);
    }
    if (message.routeId !== "") {
      writer.uint32(18).string(message.routeId);
    }
    if (message.currentAreaId !== "") {
      writer.uint32(26).string(message.currentAreaId);
    }
    if (message.occupancy !== 0) {
      writer.uint32(32).int32(message.occupancy);
    }
    if (message.ts !== undefined) {
      Timestamp.encode(toTimestamp(message.ts), writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DriverSnapshot {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDriverSnapshot();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.driverId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.routeId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.currentAreaId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.occupancy = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.ts = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DriverSnapshot {
    return {
      driverId: isSet(object.driverId) ? globalThis.String(object.driverId) : "",
      routeId: isSet(object.routeId) ? globalThis.String(object.routeId) : "",
      currentAreaId: isSet(object.currentAreaId) ? globalThis.String(object.currentAreaId) : "",
      occupancy: isSet(object.occupancy) ? globalThis.Number(object.occupancy) : 0,
      ts: isSet(object.ts) ? fromJsonTimestamp(object.ts) : undefined,
    };
  },

  toJSON(message: DriverSnapshot): unknown {
    const obj: any = {};
    if (message.driverId !== "") {
      obj.driverId = message.driverId;
    }
    if (message.routeId !== "") {
      obj.routeId = message.routeId;
    }
    if (message.currentAreaId !== "") {
      obj.currentAreaId = message.currentAreaId;
    }
    if (message.occupancy !== 0) {
      obj.occupancy = Math.round(message.occupancy);
    }
    if (message.ts !== undefined) {
      obj.ts = message.ts.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DriverSnapshot>, I>>(base?: I): DriverSnapshot {
    return DriverSnapshot.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DriverSnapshot>, I>>(object: I): DriverSnapshot {
    const message = createBaseDriverSnapshot();
    message.driverId = object.driverId ?? "";
    message.routeId = object.routeId ?? "";
    message.currentAreaId = object.currentAreaId ?? "";
    message.occupancy = object.occupancy ?? 0;
    message.ts = object.ts ?? undefined;
    return message;
  },
};

function createBaseDriverEtaRequest(): DriverEtaRequest {
  return { driverId: "", stationAreaId: "" };
}

export const DriverEtaRequest: MessageFns<DriverEtaRequest> = {
  encode(message: DriverEtaRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.driverId !== "") {
      writer.uint32(10).string(message.driverId);
    }
    if (message.stationAreaId !== "") {
      writer.uint32(18).string(message.stationAreaId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DriverEtaRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDriverEtaRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.driverId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.stationAreaId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DriverEtaRequest {
    return {
      driverId: isSet(object.driverId) ? globalThis.String(object.driverId) : "",
      stationAreaId: isSet(object.stationAreaId) ? globalThis.String(object.stationAreaId) : "",
    };
  },

  toJSON(message: DriverEtaRequest): unknown {
    const obj: any = {};
    if (message.driverId !== "") {
      obj.driverId = message.driverId;
    }
    if (message.stationAreaId !== "") {
      obj.stationAreaId = message.stationAreaId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DriverEtaRequest>, I>>(base?: I): DriverEtaRequest {
    return DriverEtaRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DriverEtaRequest>, I>>(object: I): DriverEtaRequest {
    const message = createBaseDriverEtaRequest();
    message.driverId = object.driverId ?? "";
    message.stationAreaId = object.stationAreaId ?? "";
    return message;
  },
};

function createBaseDriverEta(): DriverEta {
  return { driverId: "", stationAreaId: "", reachable: false, etaMinutes: 0 };
}

export const DriverEta: MessageFns<DriverEta> = {
  encode(message: DriverEta, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.driverId !== "") {
      writer.uint32(10).string(message.driverId);
    }
    if (message.stationAreaId !== "") {
      writer.uint32(18).string(message.stationAreaId);
    }
    if (message.reachable !== false) {
      writer.uint32(24).bool(message.reachable);
    }
    if (message.etaMinutes !== 0) {
      writer.uint32(32).int32(message.etaMinutes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DriverEta {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDriverEta();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.driverId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.stationAreaId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.reachable = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.etaMinutes = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DriverEta {
    return {
      driverId: isSet(object.driverId) ? globalThis.String(object.driverId) : "",
      stationAreaId: isSet(object.stationAreaId) ? globalThis.String(object.stationAreaId) : "",
      reachable: isSet(object.reachable) ? globalThis.Boolean(object.reachable) : false,
      etaMinutes: isSet(object.etaMinutes) ? globalThis.Number(object.etaMinutes) : 0,
    };
  },

  toJSON(message: DriverEta): unknown {
    const obj: any = {};
    if (message.driverId !== "") {
      obj.driverId = message.driverId;
    }
    if (message.stationAreaId !== "") {
      obj.stationAreaId = message.stationAreaId;
    }
    if (message.reachable !== false) {
      obj.reachable = message.reachable;
    }
    if (message.etaMinutes !== 0) {
      obj.etaMinutes = Math.round(message.etaMinutes);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DriverEta>, I>>(base?: I): DriverEta {
    return DriverEta.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DriverEta>, I>>(object: I): DriverEta {
    const message = createBaseDriverEta();
    message.driverId = object.driverId ?? "";
    message.stationAreaId = object.stationAreaId ?? "";
    message.reachable = object.reachable ?? false;
    message.etaMinutes = object.etaMinutes ?? 0;
    return message;
  },
};

function createBaseDriverId(): DriverId {
  return { id: "" };
}

export const DriverId: MessageFns<DriverId> = {
  encode(message: DriverId, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DriverId {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDriverId();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DriverId {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: DriverId): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DriverId>, I>>(base?: I): DriverId {
    return DriverId.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DriverId>, I>>(object: I): DriverId {
    const message = createBaseDriverId();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseAck(): Ack {
  return { ok: false, msg: "" };
}

export const Ack: MessageFns<Ack> = {
  encode(message: Ack, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ok !== false) {
      writer.uint32(8).bool(message.ok);
    }
    if (message.msg !== "") {
      writer.uint32(18).string(message.msg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Ack {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAck();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ok = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.msg = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Ack {
    return {
      ok: isSet(object.ok) ? globalThis.Boolean(object.ok) : false,
      msg: isSet(object.msg) ? globalThis.String(object.msg) : "",
    };
  },

  toJSON(message: Ack): unknown {
    const obj: any = {};
    if (message.ok !== false) {
      obj.ok = message.ok;
    }
    if (message.msg !== "") {
      obj.msg = message.msg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Ack>, I>>(base?: I): Ack {
    return Ack.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Ack>, I>>(object: I): Ack {
    const message = createBaseAck();
    message.ok = object.ok ?? false;
    message.msg = object.msg ?? "";
    return message;
  },
};

export interface LocationService {
  StreamDriverTelemetry(request: Observable<DriverTelemetry>): Promise<Ack>;
  UpdateDriverLocation(request: DriverTelemetry): Promise<Ack>;
  GetDriverSnapshot(request: DriverId): Promise<DriverSnapshot>;
  GetDriverEta(request: DriverEtaRequest): Promise<DriverEta>;
}

export const LocationServiceServiceName = "lastmile.location.LocationService";
export class LocationServiceClientImpl implements LocationService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || LocationServiceServiceName;
    this.rpc = rpc;
    this.StreamDriverTelemetry = this.StreamDriverTelemetry.bind(this);
    this.UpdateDriverLocation = this.UpdateDriverLocation.bind(this);
    this.GetDriverSnapshot = this.GetDriverSnapshot.bind(this);
    this.GetDriverEta = this.GetDriverEta.bind(this);
  }
  StreamDriverTelemetry(request: Observable<DriverTelemetry>): Promise<Ack> {
    const data = request.pipe(map((request) => DriverTelemetry.encode(request).finish()));
    const promise = this.rpc.clientStreamingRequest(this.service, "StreamDriverTelemetry", data);
    return promise.then((data) => Ack.decode(new BinaryReader(data)));
  }

  UpdateDriverLocation(request: DriverTelemetry): Promise<Ack> {
    const data = DriverTelemetry.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateDriverLocation", data);
    return promise.then((data) => Ack.decode(new BinaryReader(data)));
  }

  GetDriverSnapshot(request: DriverId): Promise<DriverSnapshot> {
    const data = DriverId.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetDriverSnapshot", data);
    return promise.then((data) => DriverSnapshot.decode(new BinaryReader(data)));
  }

  GetDriverEta(request: DriverEtaRequest): Promise<DriverEta> {
    const data = DriverEtaRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetDriverEta", data);
    return promise.then((data) => DriverEta.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
  clientStreamingRequest(service: string, method: string, data: Observable<Uint8Array>): Promise<Uint8Array>;
  serverStreamingRequest(service: string, method: string, data: Uint8Array): Observable<Uint8Array>;
  bidirectionalStreamingRequest(service: string, method: string, data: Observable<Uint8Array>): Observable<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
