// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.32.0
// source: matching.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Observable } from "rxjs";
import { map } from "rxjs/operators";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "lastmile.matching";

export interface EvaluateDriverRequest {
  driverId: string;
  routeId: string;
  stationAreaId: string;
  driverCurrentAreaId: string;
  destinationAreaId: string;
  seatsAvailable: number;
  etaToStationMinutes: number;
  driverLastUpdate: Date | undefined;
}

export interface MatchResult {
  tripId: string;
  driverId: string;
  stationAreaId: string;
  destinationAreaId: string;
  riderIds: string[];
  passengerCount: number;
}

export interface MatchResponse {
  matched: boolean;
  results: MatchResult[];
  msg: string;
}

export interface MatchEvent {
  eventId: string;
  stationAreaId: string;
  result: MatchResult | undefined;
}

export interface SubscribeRequest {
  clientId: string;
  stationIds: string[];
}

export interface AddRiderIntentRequest {
  riderId: string;
  stationAreaId: string;
  destinationAreaId: string;
  arrivalTime: Date | undefined;
  partySize: number;
}

export interface AddRiderIntentResponse {
  success: boolean;
  msg: string;
}

export interface CancelRideIntentRequest {
  riderId: string;
  stationAreaId: string;
}

export interface CancelRideIntentResponse {
  success: boolean;
  msg: string;
}

function createBaseEvaluateDriverRequest(): EvaluateDriverRequest {
  return {
    driverId: "",
    routeId: "",
    stationAreaId: "",
    driverCurrentAreaId: "",
    destinationAreaId: "",
    seatsAvailable: 0,
    etaToStationMinutes: 0,
    driverLastUpdate: undefined,
  };
}

export const EvaluateDriverRequest: MessageFns<EvaluateDriverRequest> = {
  encode(message: EvaluateDriverRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.driverId !== "") {
      writer.uint32(10).string(message.driverId);
    }
    if (message.routeId !== "") {
      writer.uint32(18).string(message.routeId);
    }
    if (message.stationAreaId !== "") {
      writer.uint32(26).string(message.stationAreaId);
    }
    if (message.driverCurrentAreaId !== "") {
      writer.uint32(34).string(message.driverCurrentAreaId);
    }
    if (message.destinationAreaId !== "") {
      writer.uint32(42).string(message.destinationAreaId);
    }
    if (message.seatsAvailable !== 0) {
      writer.uint32(48).int32(message.seatsAvailable);
    }
    if (message.etaToStationMinutes !== 0) {
      writer.uint32(56).int32(message.etaToStationMinutes);
    }
    if (message.driverLastUpdate !== undefined) {
      Timestamp.encode(toTimestamp(message.driverLastUpdate), writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EvaluateDriverRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEvaluateDriverRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.driverId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.routeId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.stationAreaId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.driverCurrentAreaId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.destinationAreaId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.seatsAvailable = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.etaToStationMinutes = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.driverLastUpdate = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EvaluateDriverRequest {
    return {
      driverId: isSet(object.driverId) ? globalThis.String(object.driverId) : "",
      routeId: isSet(object.routeId) ? globalThis.String(object.routeId) : "",
      stationAreaId: isSet(object.stationAreaId) ? globalThis.String(object.stationAreaId) : "",
      driverCurrentAreaId: isSet(object.driverCurrentAreaId) ? globalThis.String(object.driverCurrentAreaId) : "",
      destinationAreaId: isSet(object.destinationAreaId) ? globalThis.String(object.destinationAreaId) : "",
      seatsAvailable: isSet(object.seatsAvailable) ? globalThis.Number(object.seatsAvailable) : 0,
      etaToStationMinutes: isSet(object.etaToStationMinutes) ? globalThis.Number(object.etaToStationMinutes) : 0,
      driverLastUpdate: isSet(object.driverLastUpdate) ? fromJsonTimestamp(object.driverLastUpdate) : undefined,
    };
  },

  toJSON(message: EvaluateDriverRequest): unknown {
    const obj: any = {};
    if (message.driverId !== "") {
      obj.driverId = message.driverId;
    }
    if (message.routeId !== "") {
      obj.routeId = message.routeId;
    }
    if (message.stationAreaId !== "") {
      obj.stationAreaId = message.stationAreaId;
    }
    if (message.driverCurrentAreaId !== "") {
      obj.driverCurrentAreaId = message.driverCurrentAreaId;
    }
    if (message.destinationAreaId !== "") {
      obj.destinationAreaId = message.destinationAreaId;
    }
    if (message.seatsAvailable !== 0) {
      obj.seatsAvailable = Math.round(message.seatsAvailable);
    }
    if (message.etaToStationMinutes !== 0) {
      obj.etaToStationMinutes = Math.round(message.etaToStationMinutes);
    }
    if (message.driverLastUpdate !== undefined) {
      obj.driverLastUpdate = message.driverLastUpdate.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EvaluateDriverRequest>, I>>(base?: I): EvaluateDriverRequest {
    return EvaluateDriverRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EvaluateDriverRequest>, I>>(object: I): EvaluateDriverRequest {
    const message = createBaseEvaluateDriverRequest();
    message.driverId = object.driverId ?? "";
    message.routeId = object.routeId ?? "";
    message.stationAreaId = object.stationAreaId ?? "";
    message.driverCurrentAreaId = object.driverCurrentAreaId ?? "";
    message.destinationAreaId = object.destinationAreaId ?? "";
    message.seatsAvailable = object.seatsAvailable ?? 0;
    message.etaToStationMinutes = object.etaToStationMinutes ?? 0;
    message.driverLastUpdate = object.driverLastUpdate ?? undefined;
    return message;
  },
};

function createBaseMatchResult(): MatchResult {
  return { tripId: "", driverId: "", stationAreaId: "", destinationAreaId: "", riderIds: [], passengerCount: 0 };
}

export const MatchResult: MessageFns<MatchResult> = {
  encode(message: MatchResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tripId !== "") {
      writer.uint32(10).string(message.tripId);
    }
    if (message.driverId !== "") {
      writer.uint32(18).string(message.driverId);
    }
    if (message.stationAreaId !== "") {
      writer.uint32(26).string(message.stationAreaId);
    }
    if (message.destinationAreaId !== "") {
      writer.uint32(34).string(message.destinationAreaId);
    }
    for (const v of message.riderIds) {
      writer.uint32(42).string(v!);
    }
    if (message.passengerCount !== 0) {
      writer.uint32(48).int32(message.passengerCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MatchResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMatchResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tripId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.driverId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.stationAreaId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.destinationAreaId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.riderIds.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.passengerCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MatchResult {
    return {
      tripId: isSet(object.tripId) ? globalThis.String(object.tripId) : "",
      driverId: isSet(object.driverId) ? globalThis.String(object.driverId) : "",
      stationAreaId: isSet(object.stationAreaId) ? globalThis.String(object.stationAreaId) : "",
      destinationAreaId: isSet(object.destinationAreaId) ? globalThis.String(object.destinationAreaId) : "",
      riderIds: globalThis.Array.isArray(object?.riderIds) ? object.riderIds.map((e: any) => globalThis.String(e)) : [],
      passengerCount: isSet(object.passengerCount) ? globalThis.Number(object.passengerCount) : 0,
    };
  },

  toJSON(message: MatchResult): unknown {
    const obj: any = {};
    if (message.tripId !== "") {
      obj.tripId = message.tripId;
    }
    if (message.driverId !== "") {
      obj.driverId = message.driverId;
    }
    if (message.stationAreaId !== "") {
      obj.stationAreaId = message.stationAreaId;
    }
    if (message.destinationAreaId !== "") {
      obj.destinationAreaId = message.destinationAreaId;
    }
    if (message.riderIds?.length) {
      obj.riderIds = message.riderIds;
    }
    if (message.passengerCount !== 0) {
      obj.passengerCount = Math.round(message.passengerCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MatchResult>, I>>(base?: I): MatchResult {
    return MatchResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MatchResult>, I>>(object: I): MatchResult {
    const message = createBaseMatchResult();
    message.tripId = object.tripId ?? "";
    message.driverId = object.driverId ?? "";
    message.stationAreaId = object.stationAreaId ?? "";
    message.destinationAreaId = object.destinationAreaId ?? "";
    message.riderIds = object.riderIds?.map((e) => e) || [];
    message.passengerCount = object.passengerCount ?? 0;
    return message;
  },
};

function createBaseMatchResponse(): MatchResponse {
  return { matched: false, results: [], msg: "" };
}

export const MatchResponse: MessageFns<MatchResponse> = {
  encode(message: MatchResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.matched !== false) {
      writer.uint32(8).bool(message.matched);
    }
    for (const v of message.results) {
      MatchResult.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.msg !== "") {
      writer.uint32(26).string(message.msg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MatchResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMatchResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.matched = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.results.push(MatchResult.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.msg = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MatchResponse {
    return {
      matched: isSet(object.matched) ? globalThis.Boolean(object.matched) : false,
      results: globalThis.Array.isArray(object?.results) ? object.results.map((e: any) => MatchResult.fromJSON(e)) : [],
      msg: isSet(object.msg) ? globalThis.String(object.msg) : "",
    };
  },

  toJSON(message: MatchResponse): unknown {
    const obj: any = {};
    if (message.matched !== false) {
      obj.matched = message.matched;
    }
    if (message.results?.length) {
      obj.results = message.results.map((e) => MatchResult.toJSON(e));
    }
    if (message.msg !== "") {
      obj.msg = message.msg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MatchResponse>, I>>(base?: I): MatchResponse {
    return MatchResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MatchResponse>, I>>(object: I): MatchResponse {
    const message = createBaseMatchResponse();
    message.matched = object.matched ?? false;
    message.results = object.results?.map((e) => MatchResult.fromPartial(e)) || [];
    message.msg = object.msg ?? "";
    return message;
  },
};

function createBaseMatchEvent(): MatchEvent {
  return { eventId: "", stationAreaId: "", result: undefined };
}

export const MatchEvent: MessageFns<MatchEvent> = {
  encode(message: MatchEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventId !== "") {
      writer.uint32(10).string(message.eventId);
    }
    if (message.stationAreaId !== "") {
      writer.uint32(18).string(message.stationAreaId);
    }
    if (message.result !== undefined) {
      MatchResult.encode(message.result, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MatchEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMatchEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.eventId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.stationAreaId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.result = MatchResult.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MatchEvent {
    return {
      eventId: isSet(object.eventId) ? globalThis.String(object.eventId) : "",
      stationAreaId: isSet(object.stationAreaId) ? globalThis.String(object.stationAreaId) : "",
      result: isSet(object.result) ? MatchResult.fromJSON(object.result) : undefined,
    };
  },

  toJSON(message: MatchEvent): unknown {
    const obj: any = {};
    if (message.eventId !== "") {
      obj.eventId = message.eventId;
    }
    if (message.stationAreaId !== "") {
      obj.stationAreaId = message.stationAreaId;
    }
    if (message.result !== undefined) {
      obj.result = MatchResult.toJSON(message.result);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MatchEvent>, I>>(base?: I): MatchEvent {
    return MatchEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MatchEvent>, I>>(object: I): MatchEvent {
    const message = createBaseMatchEvent();
    message.eventId = object.eventId ?? "";
    message.stationAreaId = object.stationAreaId ?? "";
    message.result = (object.result !== undefined && object.result !== null)
      ? MatchResult.fromPartial(object.result)
      : undefined;
    return message;
  },
};

function createBaseSubscribeRequest(): SubscribeRequest {
  return { clientId: "", stationIds: [] };
}

export const SubscribeRequest: MessageFns<SubscribeRequest> = {
  encode(message: SubscribeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientId !== "") {
      writer.uint32(10).string(message.clientId);
    }
    for (const v of message.stationIds) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubscribeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscribeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.stationIds.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubscribeRequest {
    return {
      clientId: isSet(object.clientId) ? globalThis.String(object.clientId) : "",
      stationIds: globalThis.Array.isArray(object?.stationIds)
        ? object.stationIds.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: SubscribeRequest): unknown {
    const obj: any = {};
    if (message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    if (message.stationIds?.length) {
      obj.stationIds = message.stationIds;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubscribeRequest>, I>>(base?: I): SubscribeRequest {
    return SubscribeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubscribeRequest>, I>>(object: I): SubscribeRequest {
    const message = createBaseSubscribeRequest();
    message.clientId = object.clientId ?? "";
    message.stationIds = object.stationIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseAddRiderIntentRequest(): AddRiderIntentRequest {
  return { riderId: "", stationAreaId: "", destinationAreaId: "", arrivalTime: undefined, partySize: 0 };
}

export const AddRiderIntentRequest: MessageFns<AddRiderIntentRequest> = {
  encode(message: AddRiderIntentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.riderId !== "") {
      writer.uint32(10).string(message.riderId);
    }
    if (message.stationAreaId !== "") {
      writer.uint32(18).string(message.stationAreaId);
    }
    if (message.destinationAreaId !== "") {
      writer.uint32(26).string(message.destinationAreaId);
    }
    if (message.arrivalTime !== undefined) {
      Timestamp.encode(toTimestamp(message.arrivalTime), writer.uint32(34).fork()).join();
    }
    if (message.partySize !== 0) {
      writer.uint32(40).int32(message.partySize);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddRiderIntentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddRiderIntentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.riderId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.stationAreaId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.destinationAreaId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.arrivalTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.partySize = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddRiderIntentRequest {
    return {
      riderId: isSet(object.riderId) ? globalThis.String(object.riderId) : "",
      stationAreaId: isSet(object.stationAreaId) ? globalThis.String(object.stationAreaId) : "",
      destinationAreaId: isSet(object.destinationAreaId) ? globalThis.String(object.destinationAreaId) : "",
      arrivalTime: isSet(object.arrivalTime) ? fromJsonTimestamp(object.arrivalTime) : undefined,
      partySize: isSet(object.partySize) ? globalThis.Number(object.partySize) : 0,
    };
  },

  toJSON(message: AddRiderIntentRequest): unknown {
    const obj: any = {};
    if (message.riderId !== "") {
      obj.riderId = message.riderId;
    }
    if (message.stationAreaId !== "") {
      obj.stationAreaId = message.stationAreaId;
    }
    if (message.destinationAreaId !== "") {
      obj.destinationAreaId = message.destinationAreaId;
    }
    if (message.arrivalTime !== undefined) {
      obj.arrivalTime = message.arrivalTime.toISOString();
    }
    if (message.partySize !== 0) {
      obj.partySize = Math.round(message.partySize);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddRiderIntentRequest>, I>>(base?: I): AddRiderIntentRequest {
    return AddRiderIntentRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddRiderIntentRequest>, I>>(object: I): AddRiderIntentRequest {
    const message = createBaseAddRiderIntentRequest();
    message.riderId = object.riderId ?? "";
    message.stationAreaId = object.stationAreaId ?? "";
    message.destinationAreaId = object.destinationAreaId ?? "";
    message.arrivalTime = object.arrivalTime ?? undefined;
    message.partySize = object.partySize ?? 0;
    return message;
  },
};

function createBaseAddRiderIntentResponse(): AddRiderIntentResponse {
  return { success: false, msg: "" };
}

export const AddRiderIntentResponse: MessageFns<AddRiderIntentResponse> = {
  encode(message: AddRiderIntentResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.msg !== "") {
      writer.uint32(18).string(message.msg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddRiderIntentResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddRiderIntentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.msg = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddRiderIntentResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      msg: isSet(object.msg) ? globalThis.String(object.msg) : "",
    };
  },

  toJSON(message: AddRiderIntentResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.msg !== "") {
      obj.msg = message.msg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddRiderIntentResponse>, I>>(base?: I): AddRiderIntentResponse {
    return AddRiderIntentResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddRiderIntentResponse>, I>>(object: I): AddRiderIntentResponse {
    const message = createBaseAddRiderIntentResponse();
    message.success = object.success ?? false;
    message.msg = object.msg ?? "";
    return message;
  },
};

function createBaseCancelRideIntentRequest(): CancelRideIntentRequest {
  return { riderId: "", stationAreaId: "" };
}

export const CancelRideIntentRequest: MessageFns<CancelRideIntentRequest> = {
  encode(message: CancelRideIntentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.riderId !== "") {
      writer.uint32(10).string(message.riderId);
    }
    if (message.stationAreaId !== "") {
      writer.uint32(18).string(message.stationAreaId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CancelRideIntentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCancelRideIntentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.riderId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.stationAreaId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CancelRideIntentRequest {
    return {
      riderId: isSet(object.riderId) ? globalThis.String(object.riderId) : "",
      stationAreaId: isSet(object.stationAreaId) ? globalThis.String(object.stationAreaId) : "",
    };
  },

  toJSON(message: CancelRideIntentRequest): unknown {
    const obj: any = {};
    if (message.riderId !== "") {
      obj.riderId = message.riderId;
    }
    if (message.stationAreaId !== "") {
      obj.stationAreaId = message.stationAreaId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CancelRideIntentRequest>, I>>(base?: I): CancelRideIntentRequest {
    return CancelRideIntentRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CancelRideIntentRequest>, I>>(object: I): CancelRideIntentRequest {
    const message = createBaseCancelRideIntentRequest();
    message.riderId = object.riderId ?? "";
    message.stationAreaId = object.stationAreaId ?? "";
    return message;
  },
};

function createBaseCancelRideIntentResponse(): CancelRideIntentResponse {
  return { success: false, msg: "" };
}

export const CancelRideIntentResponse: MessageFns<CancelRideIntentResponse> = {
  encode(message: CancelRideIntentResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.msg !== "") {
      writer.uint32(18).string(message.msg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CancelRideIntentResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCancelRideIntentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.msg = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CancelRideIntentResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      msg: isSet(object.msg) ? globalThis.String(object.msg) : "",
    };
  },

  toJSON(message: CancelRideIntentResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.msg !== "") {
      obj.msg = message.msg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CancelRideIntentResponse>, I>>(base?: I): CancelRideIntentResponse {
    return CancelRideIntentResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CancelRideIntentResponse>, I>>(object: I): CancelRideIntentResponse {
    const message = createBaseCancelRideIntentResponse();
    message.success = object.success ?? false;
    message.msg = object.msg ?? "";
    return message;
  },
};

export interface MatchingService {
  EvaluateDriver(request: EvaluateDriverRequest): Promise<MatchResponse>;
  SubscribeMatches(request: SubscribeRequest): Observable<MatchEvent>;
  AddRiderIntent(request: AddRiderIntentRequest): Promise<AddRiderIntentResponse>;
  CancelRideIntent(request: CancelRideIntentRequest): Promise<CancelRideIntentResponse>;
}

export const MatchingServiceServiceName = "lastmile.matching.MatchingService";
export class MatchingServiceClientImpl implements MatchingService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MatchingServiceServiceName;
    this.rpc = rpc;
    this.EvaluateDriver = this.EvaluateDriver.bind(this);
    this.SubscribeMatches = this.SubscribeMatches.bind(this);
    this.AddRiderIntent = this.AddRiderIntent.bind(this);
    this.CancelRideIntent = this.CancelRideIntent.bind(this);
  }
  EvaluateDriver(request: EvaluateDriverRequest): Promise<MatchResponse> {
    const data = EvaluateDriverRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "EvaluateDriver", data);
    return promise.then((data) => MatchResponse.decode(new BinaryReader(data)));
  }

  SubscribeMatches(request: SubscribeRequest): Observable<MatchEvent> {
    const data = SubscribeRequest.encode(request).finish();
    const result = this.rpc.serverStreamingRequest(this.service, "SubscribeMatches", data);
    return result.pipe(map((data) => MatchEvent.decode(new BinaryReader(data))));
  }

  AddRiderIntent(request: AddRiderIntentRequest): Promise<AddRiderIntentResponse> {
    const data = AddRiderIntentRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "AddRiderIntent", data);
    return promise.then((data) => AddRiderIntentResponse.decode(new BinaryReader(data)));
  }

  CancelRideIntent(request: CancelRideIntentRequest): Promise<CancelRideIntentResponse> {
    const data = CancelRideIntentRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "CancelRideIntent", data);
    return promise.then((data) => CancelRideIntentResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
  clientStreamingRequest(service: string, method: string, data: Observable<Uint8Array>): Promise<Uint8Array>;
  serverStreamingRequest(service: string, method: string, data: Uint8Array): Observable<Uint8Array>;
  bidirectionalStreamingRequest(service: string, method: string, data: Observable<Uint8Array>): Observable<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
