// source: rider.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

import common_pb from './common_pb.js';
import * as jspb from 'google-protobuf';
var goog = jspb;
var global =
  (typeof globalThis !== 'undefined' && globalThis) ||
  (typeof window !== 'undefined' && window) ||
  (typeof global !== 'undefined' && global) ||
  (typeof self !== 'undefined' && self) ||
  (function () { return this; }).call(null) ||
  Function('return this')();

import * as google_protobuf_timestamp_pb from 'google-protobuf/google/protobuf/timestamp_pb.js';
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.lastmile.rider.GetRideHistoryRequest', null, global);
goog.exportSymbol('proto.lastmile.rider.RegisterRideIntentRequest', null, global);
goog.exportSymbol('proto.lastmile.rider.RideHistoryResponse', null, global);
goog.exportSymbol('proto.lastmile.rider.RideId', null, global);
goog.exportSymbol('proto.lastmile.rider.RideIntentResponse', null, global);
goog.exportSymbol('proto.lastmile.rider.RideStatus', null, global);
goog.exportSymbol('proto.lastmile.rider.RideStatus.Status', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.lastmile.rider.RegisterRideIntentRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.lastmile.rider.RegisterRideIntentRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.lastmile.rider.RegisterRideIntentRequest.displayName = 'proto.lastmile.rider.RegisterRideIntentRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.lastmile.rider.RideIntentResponse = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.lastmile.rider.RideIntentResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.lastmile.rider.RideIntentResponse.displayName = 'proto.lastmile.rider.RideIntentResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.lastmile.rider.RideId = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.lastmile.rider.RideId, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.lastmile.rider.RideId.displayName = 'proto.lastmile.rider.RideId';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.lastmile.rider.RideStatus = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.lastmile.rider.RideStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.lastmile.rider.RideStatus.displayName = 'proto.lastmile.rider.RideStatus';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.lastmile.rider.GetRideHistoryRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.lastmile.rider.GetRideHistoryRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.lastmile.rider.GetRideHistoryRequest.displayName = 'proto.lastmile.rider.GetRideHistoryRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.lastmile.rider.RideHistoryResponse = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.lastmile.rider.RideHistoryResponse.repeatedFields_, null);
};
goog.inherits(proto.lastmile.rider.RideHistoryResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.lastmile.rider.RideHistoryResponse.displayName = 'proto.lastmile.rider.RideHistoryResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.lastmile.rider.RegisterRideIntentRequest.prototype.toObject = function (opt_includeInstance) {
    return proto.lastmile.rider.RegisterRideIntentRequest.toObject(opt_includeInstance, this);
  };


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.lastmile.rider.RegisterRideIntentRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.lastmile.rider.RegisterRideIntentRequest.toObject = function (includeInstance, msg) {
    var f, obj = {
      userId: jspb.Message.getFieldWithDefault(msg, 1, ""),
      stationAreaId: jspb.Message.getFieldWithDefault(msg, 2, ""),
      arrivalTime: (f = msg.getArrivalTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
      destinationAreaId: jspb.Message.getFieldWithDefault(msg, 4, ""),
      partySize: jspb.Message.getFieldWithDefault(msg, 5, 0)
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.lastmile.rider.RegisterRideIntentRequest}
 */
proto.lastmile.rider.RegisterRideIntentRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.lastmile.rider.RegisterRideIntentRequest;
  return proto.lastmile.rider.RegisterRideIntentRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.lastmile.rider.RegisterRideIntentRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.lastmile.rider.RegisterRideIntentRequest}
 */
proto.lastmile.rider.RegisterRideIntentRequest.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setUserId(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setStationAreaId(value);
        break;
      case 3:
        var value = new google_protobuf_timestamp_pb.Timestamp;
        reader.readMessage(value, google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
        msg.setArrivalTime(value);
        break;
      case 4:
        var value = /** @type {string} */ (reader.readString());
        msg.setDestinationAreaId(value);
        break;
      case 5:
        var value = /** @type {number} */ (reader.readInt32());
        msg.setPartySize(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.lastmile.rider.RegisterRideIntentRequest.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.lastmile.rider.RegisterRideIntentRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.lastmile.rider.RegisterRideIntentRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lastmile.rider.RegisterRideIntentRequest.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStationAreaId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getArrivalTime();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDestinationAreaId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getPartySize();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
};


/**
 * optional string user_id = 1;
 * @return {string}
 */
proto.lastmile.rider.RegisterRideIntentRequest.prototype.getUserId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.lastmile.rider.RegisterRideIntentRequest} returns this
 */
proto.lastmile.rider.RegisterRideIntentRequest.prototype.setUserId = function (value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string station_area_id = 2;
 * @return {string}
 */
proto.lastmile.rider.RegisterRideIntentRequest.prototype.getStationAreaId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.lastmile.rider.RegisterRideIntentRequest} returns this
 */
proto.lastmile.rider.RegisterRideIntentRequest.prototype.setStationAreaId = function (value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp arrival_time = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.lastmile.rider.RegisterRideIntentRequest.prototype.getArrivalTime = function () {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.lastmile.rider.RegisterRideIntentRequest} returns this
*/
proto.lastmile.rider.RegisterRideIntentRequest.prototype.setArrivalTime = function (value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.lastmile.rider.RegisterRideIntentRequest} returns this
 */
proto.lastmile.rider.RegisterRideIntentRequest.prototype.clearArrivalTime = function () {
  return this.setArrivalTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.lastmile.rider.RegisterRideIntentRequest.prototype.hasArrivalTime = function () {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string destination_area_id = 4;
 * @return {string}
 */
proto.lastmile.rider.RegisterRideIntentRequest.prototype.getDestinationAreaId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.lastmile.rider.RegisterRideIntentRequest} returns this
 */
proto.lastmile.rider.RegisterRideIntentRequest.prototype.setDestinationAreaId = function (value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 party_size = 5;
 * @return {number}
 */
proto.lastmile.rider.RegisterRideIntentRequest.prototype.getPartySize = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.lastmile.rider.RegisterRideIntentRequest} returns this
 */
proto.lastmile.rider.RegisterRideIntentRequest.prototype.setPartySize = function (value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.lastmile.rider.RideIntentResponse.prototype.toObject = function (opt_includeInstance) {
    return proto.lastmile.rider.RideIntentResponse.toObject(opt_includeInstance, this);
  };


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.lastmile.rider.RideIntentResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.lastmile.rider.RideIntentResponse.toObject = function (includeInstance, msg) {
    var f, obj = {
      intentId: jspb.Message.getFieldWithDefault(msg, 1, "")
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.lastmile.rider.RideIntentResponse}
 */
proto.lastmile.rider.RideIntentResponse.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.lastmile.rider.RideIntentResponse;
  return proto.lastmile.rider.RideIntentResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.lastmile.rider.RideIntentResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.lastmile.rider.RideIntentResponse}
 */
proto.lastmile.rider.RideIntentResponse.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setIntentId(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.lastmile.rider.RideIntentResponse.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.lastmile.rider.RideIntentResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.lastmile.rider.RideIntentResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lastmile.rider.RideIntentResponse.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getIntentId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string intent_id = 1;
 * @return {string}
 */
proto.lastmile.rider.RideIntentResponse.prototype.getIntentId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.lastmile.rider.RideIntentResponse} returns this
 */
proto.lastmile.rider.RideIntentResponse.prototype.setIntentId = function (value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.lastmile.rider.RideId.prototype.toObject = function (opt_includeInstance) {
    return proto.lastmile.rider.RideId.toObject(opt_includeInstance, this);
  };


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.lastmile.rider.RideId} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.lastmile.rider.RideId.toObject = function (includeInstance, msg) {
    var f, obj = {
      id: jspb.Message.getFieldWithDefault(msg, 1, "")
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.lastmile.rider.RideId}
 */
proto.lastmile.rider.RideId.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.lastmile.rider.RideId;
  return proto.lastmile.rider.RideId.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.lastmile.rider.RideId} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.lastmile.rider.RideId}
 */
proto.lastmile.rider.RideId.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setId(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.lastmile.rider.RideId.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.lastmile.rider.RideId.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.lastmile.rider.RideId} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lastmile.rider.RideId.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.lastmile.rider.RideId.prototype.getId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.lastmile.rider.RideId} returns this
 */
proto.lastmile.rider.RideId.prototype.setId = function (value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.lastmile.rider.RideStatus.prototype.toObject = function (opt_includeInstance) {
    return proto.lastmile.rider.RideStatus.toObject(opt_includeInstance, this);
  };


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.lastmile.rider.RideStatus} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.lastmile.rider.RideStatus.toObject = function (includeInstance, msg) {
    var f, obj = {
      intentId: jspb.Message.getFieldWithDefault(msg, 1, ""),
      status: jspb.Message.getFieldWithDefault(msg, 2, 0),
      tripId: jspb.Message.getFieldWithDefault(msg, 3, ""),
      destinationAreaId: jspb.Message.getFieldWithDefault(msg, 4, ""),
      stationAreaId: jspb.Message.getFieldWithDefault(msg, 5, "")
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.lastmile.rider.RideStatus}
 */
proto.lastmile.rider.RideStatus.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.lastmile.rider.RideStatus;
  return proto.lastmile.rider.RideStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.lastmile.rider.RideStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.lastmile.rider.RideStatus}
 */
proto.lastmile.rider.RideStatus.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setIntentId(value);
        break;
      case 2:
        var value = /** @type {!proto.lastmile.rider.RideStatus.Status} */ (reader.readEnum());
        msg.setStatus(value);
        break;
      case 3:
        var value = /** @type {string} */ (reader.readString());
        msg.setTripId(value);
        break;
      case 4:
        var value = /** @type {string} */ (reader.readString());
        msg.setDestinationAreaId(value);
        break;
      case 5:
        var value = /** @type {string} */ (reader.readString());
        msg.setStationAreaId(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.lastmile.rider.RideStatus.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.lastmile.rider.RideStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.lastmile.rider.RideStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lastmile.rider.RideStatus.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getIntentId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getTripId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDestinationAreaId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getStationAreaId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.lastmile.rider.RideStatus.Status = {
  PENDING: 0,
  SCHEDULED: 1,
  PICKED_UP: 2,
  COMPLETED: 3,
  CANCELLED: 4
};

/**
 * optional string intent_id = 1;
 * @return {string}
 */
proto.lastmile.rider.RideStatus.prototype.getIntentId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.lastmile.rider.RideStatus} returns this
 */
proto.lastmile.rider.RideStatus.prototype.setIntentId = function (value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Status status = 2;
 * @return {!proto.lastmile.rider.RideStatus.Status}
 */
proto.lastmile.rider.RideStatus.prototype.getStatus = function () {
  return /** @type {!proto.lastmile.rider.RideStatus.Status} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.lastmile.rider.RideStatus.Status} value
 * @return {!proto.lastmile.rider.RideStatus} returns this
 */
proto.lastmile.rider.RideStatus.prototype.setStatus = function (value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string trip_id = 3;
 * @return {string}
 */
proto.lastmile.rider.RideStatus.prototype.getTripId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.lastmile.rider.RideStatus} returns this
 */
proto.lastmile.rider.RideStatus.prototype.setTripId = function (value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string destination_area_id = 4;
 * @return {string}
 */
proto.lastmile.rider.RideStatus.prototype.getDestinationAreaId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.lastmile.rider.RideStatus} returns this
 */
proto.lastmile.rider.RideStatus.prototype.setDestinationAreaId = function (value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string station_area_id = 5;
 * @return {string}
 */
proto.lastmile.rider.RideStatus.prototype.getStationAreaId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.lastmile.rider.RideStatus} returns this
 */
proto.lastmile.rider.RideStatus.prototype.setStationAreaId = function (value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.lastmile.rider.GetRideHistoryRequest.prototype.toObject = function (opt_includeInstance) {
    return proto.lastmile.rider.GetRideHistoryRequest.toObject(opt_includeInstance, this);
  };


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.lastmile.rider.GetRideHistoryRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.lastmile.rider.GetRideHistoryRequest.toObject = function (includeInstance, msg) {
    var f, obj = {
      userId: jspb.Message.getFieldWithDefault(msg, 1, "")
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.lastmile.rider.GetRideHistoryRequest}
 */
proto.lastmile.rider.GetRideHistoryRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.lastmile.rider.GetRideHistoryRequest;
  return proto.lastmile.rider.GetRideHistoryRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.lastmile.rider.GetRideHistoryRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.lastmile.rider.GetRideHistoryRequest}
 */
proto.lastmile.rider.GetRideHistoryRequest.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setUserId(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.lastmile.rider.GetRideHistoryRequest.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.lastmile.rider.GetRideHistoryRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.lastmile.rider.GetRideHistoryRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lastmile.rider.GetRideHistoryRequest.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string user_id = 1;
 * @return {string}
 */
proto.lastmile.rider.GetRideHistoryRequest.prototype.getUserId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.lastmile.rider.GetRideHistoryRequest} returns this
 */
proto.lastmile.rider.GetRideHistoryRequest.prototype.setUserId = function (value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.lastmile.rider.RideHistoryResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.lastmile.rider.RideHistoryResponse.prototype.toObject = function (opt_includeInstance) {
    return proto.lastmile.rider.RideHistoryResponse.toObject(opt_includeInstance, this);
  };


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.lastmile.rider.RideHistoryResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.lastmile.rider.RideHistoryResponse.toObject = function (includeInstance, msg) {
    var f, obj = {
      ridesList: jspb.Message.toObjectList(msg.getRidesList(),
        proto.lastmile.rider.RideStatus.toObject, includeInstance)
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.lastmile.rider.RideHistoryResponse}
 */
proto.lastmile.rider.RideHistoryResponse.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.lastmile.rider.RideHistoryResponse;
  return proto.lastmile.rider.RideHistoryResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.lastmile.rider.RideHistoryResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.lastmile.rider.RideHistoryResponse}
 */
proto.lastmile.rider.RideHistoryResponse.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = new proto.lastmile.rider.RideStatus;
        reader.readMessage(value, proto.lastmile.rider.RideStatus.deserializeBinaryFromReader);
        msg.addRides(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.lastmile.rider.RideHistoryResponse.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.lastmile.rider.RideHistoryResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.lastmile.rider.RideHistoryResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.lastmile.rider.RideHistoryResponse.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getRidesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.lastmile.rider.RideStatus.serializeBinaryToWriter
    );
  }
};


/**
 * repeated RideStatus rides = 1;
 * @return {!Array<!proto.lastmile.rider.RideStatus>}
 */
proto.lastmile.rider.RideHistoryResponse.prototype.getRidesList = function () {
  return /** @type{!Array<!proto.lastmile.rider.RideStatus>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.lastmile.rider.RideStatus, 1));
};


/**
 * @param {!Array<!proto.lastmile.rider.RideStatus>} value
 * @return {!proto.lastmile.rider.RideHistoryResponse} returns this
*/
proto.lastmile.rider.RideHistoryResponse.prototype.setRidesList = function (value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.lastmile.rider.RideStatus=} opt_value
 * @param {number=} opt_index
 * @return {!proto.lastmile.rider.RideStatus}
 */
proto.lastmile.rider.RideHistoryResponse.prototype.addRides = function (opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.lastmile.rider.RideStatus, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.lastmile.rider.RideHistoryResponse} returns this
 */
proto.lastmile.rider.RideHistoryResponse.prototype.clearRidesList = function () {
  return this.setRidesList([]);
};


export default proto.lastmile.rider;
export const GetRideHistoryRequest = proto.lastmile.rider.GetRideHistoryRequest;
export const RegisterRideIntentRequest = proto.lastmile.rider.RegisterRideIntentRequest;
export const RideHistoryResponse = proto.lastmile.rider.RideHistoryResponse;
export const RideId = proto.lastmile.rider.RideId;
export const RideIntentResponse = proto.lastmile.rider.RideIntentResponse;
export const RideStatus = proto.lastmile.rider.RideStatus;
