// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.32.0
// source: station.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Area } from "./common";

export const protobufPackage = "lastmile.station";

export interface AreaId {
  id: string;
}

export interface AreaList {
  items: Area[];
}

export interface ListAreasRequest {
}

export interface ListStationsRequest {
}

function createBaseAreaId(): AreaId {
  return { id: "" };
}

export const AreaId: MessageFns<AreaId> = {
  encode(message: AreaId, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AreaId {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAreaId();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AreaId {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: AreaId): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AreaId>, I>>(base?: I): AreaId {
    return AreaId.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AreaId>, I>>(object: I): AreaId {
    const message = createBaseAreaId();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseAreaList(): AreaList {
  return { items: [] };
}

export const AreaList: MessageFns<AreaList> = {
  encode(message: AreaList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.items) {
      Area.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AreaList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAreaList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items.push(Area.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AreaList {
    return { items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => Area.fromJSON(e)) : [] };
  },

  toJSON(message: AreaList): unknown {
    const obj: any = {};
    if (message.items?.length) {
      obj.items = message.items.map((e) => Area.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AreaList>, I>>(base?: I): AreaList {
    return AreaList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AreaList>, I>>(object: I): AreaList {
    const message = createBaseAreaList();
    message.items = object.items?.map((e) => Area.fromPartial(e)) || [];
    return message;
  },
};

function createBaseListAreasRequest(): ListAreasRequest {
  return {};
}

export const ListAreasRequest: MessageFns<ListAreasRequest> = {
  encode(_: ListAreasRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListAreasRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListAreasRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ListAreasRequest {
    return {};
  },

  toJSON(_: ListAreasRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ListAreasRequest>, I>>(base?: I): ListAreasRequest {
    return ListAreasRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListAreasRequest>, I>>(_: I): ListAreasRequest {
    const message = createBaseListAreasRequest();
    return message;
  },
};

function createBaseListStationsRequest(): ListStationsRequest {
  return {};
}

export const ListStationsRequest: MessageFns<ListStationsRequest> = {
  encode(_: ListStationsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListStationsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListStationsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ListStationsRequest {
    return {};
  },

  toJSON(_: ListStationsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ListStationsRequest>, I>>(base?: I): ListStationsRequest {
    return ListStationsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListStationsRequest>, I>>(_: I): ListStationsRequest {
    const message = createBaseListStationsRequest();
    return message;
  },
};

export interface StationService {
  GetArea(request: AreaId): Promise<Area>;
  ListAreas(request: ListAreasRequest): Promise<AreaList>;
  ListStations(request: ListStationsRequest): Promise<AreaList>;
}

export const StationServiceServiceName = "lastmile.station.StationService";
export class StationServiceClientImpl implements StationService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || StationServiceServiceName;
    this.rpc = rpc;
    this.GetArea = this.GetArea.bind(this);
    this.ListAreas = this.ListAreas.bind(this);
    this.ListStations = this.ListStations.bind(this);
  }
  GetArea(request: AreaId): Promise<Area> {
    const data = AreaId.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetArea", data);
    return promise.then((data) => Area.decode(new BinaryReader(data)));
  }

  ListAreas(request: ListAreasRequest): Promise<AreaList> {
    const data = ListAreasRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListAreas", data);
    return promise.then((data) => AreaList.decode(new BinaryReader(data)));
  }

  ListStations(request: ListStationsRequest): Promise<AreaList> {
    const data = ListStationsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListStations", data);
    return promise.then((data) => AreaList.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
