// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.32.0
// source: trip.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "lastmile.trip";

export interface CreateTripRequest {
  driverId: string;
  routeId: string;
  stationAreaId: string;
  riderIds: string[];
  destinationAreaId: string;
  scheduledDeparture: Date | undefined;
}

export interface Trip {
  tripId: string;
  driverId: string;
  routeId: string;
  stationAreaId: string;
  destinationAreaId: string;
  riderIds: string[];
  status: string;
  scheduledDeparture: Date | undefined;
}

export interface UpdateTripRequest {
  tripId: string;
  status: string;
}

export interface TripId {
  id: string;
}

export interface GetTripsRequest {
  driverId: string;
  riderId: string;
}

export interface GetTripsResponse {
  trips: Trip[];
}

function createBaseCreateTripRequest(): CreateTripRequest {
  return {
    driverId: "",
    routeId: "",
    stationAreaId: "",
    riderIds: [],
    destinationAreaId: "",
    scheduledDeparture: undefined,
  };
}

export const CreateTripRequest: MessageFns<CreateTripRequest> = {
  encode(message: CreateTripRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.driverId !== "") {
      writer.uint32(10).string(message.driverId);
    }
    if (message.routeId !== "") {
      writer.uint32(18).string(message.routeId);
    }
    if (message.stationAreaId !== "") {
      writer.uint32(26).string(message.stationAreaId);
    }
    for (const v of message.riderIds) {
      writer.uint32(34).string(v!);
    }
    if (message.destinationAreaId !== "") {
      writer.uint32(42).string(message.destinationAreaId);
    }
    if (message.scheduledDeparture !== undefined) {
      Timestamp.encode(toTimestamp(message.scheduledDeparture), writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateTripRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateTripRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.driverId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.routeId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.stationAreaId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.riderIds.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.destinationAreaId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.scheduledDeparture = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateTripRequest {
    return {
      driverId: isSet(object.driverId) ? globalThis.String(object.driverId) : "",
      routeId: isSet(object.routeId) ? globalThis.String(object.routeId) : "",
      stationAreaId: isSet(object.stationAreaId) ? globalThis.String(object.stationAreaId) : "",
      riderIds: globalThis.Array.isArray(object?.riderIds) ? object.riderIds.map((e: any) => globalThis.String(e)) : [],
      destinationAreaId: isSet(object.destinationAreaId) ? globalThis.String(object.destinationAreaId) : "",
      scheduledDeparture: isSet(object.scheduledDeparture) ? fromJsonTimestamp(object.scheduledDeparture) : undefined,
    };
  },

  toJSON(message: CreateTripRequest): unknown {
    const obj: any = {};
    if (message.driverId !== "") {
      obj.driverId = message.driverId;
    }
    if (message.routeId !== "") {
      obj.routeId = message.routeId;
    }
    if (message.stationAreaId !== "") {
      obj.stationAreaId = message.stationAreaId;
    }
    if (message.riderIds?.length) {
      obj.riderIds = message.riderIds;
    }
    if (message.destinationAreaId !== "") {
      obj.destinationAreaId = message.destinationAreaId;
    }
    if (message.scheduledDeparture !== undefined) {
      obj.scheduledDeparture = message.scheduledDeparture.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateTripRequest>, I>>(base?: I): CreateTripRequest {
    return CreateTripRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateTripRequest>, I>>(object: I): CreateTripRequest {
    const message = createBaseCreateTripRequest();
    message.driverId = object.driverId ?? "";
    message.routeId = object.routeId ?? "";
    message.stationAreaId = object.stationAreaId ?? "";
    message.riderIds = object.riderIds?.map((e) => e) || [];
    message.destinationAreaId = object.destinationAreaId ?? "";
    message.scheduledDeparture = object.scheduledDeparture ?? undefined;
    return message;
  },
};

function createBaseTrip(): Trip {
  return {
    tripId: "",
    driverId: "",
    routeId: "",
    stationAreaId: "",
    destinationAreaId: "",
    riderIds: [],
    status: "",
    scheduledDeparture: undefined,
  };
}

export const Trip: MessageFns<Trip> = {
  encode(message: Trip, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tripId !== "") {
      writer.uint32(10).string(message.tripId);
    }
    if (message.driverId !== "") {
      writer.uint32(18).string(message.driverId);
    }
    if (message.routeId !== "") {
      writer.uint32(26).string(message.routeId);
    }
    if (message.stationAreaId !== "") {
      writer.uint32(34).string(message.stationAreaId);
    }
    if (message.destinationAreaId !== "") {
      writer.uint32(42).string(message.destinationAreaId);
    }
    for (const v of message.riderIds) {
      writer.uint32(50).string(v!);
    }
    if (message.status !== "") {
      writer.uint32(58).string(message.status);
    }
    if (message.scheduledDeparture !== undefined) {
      Timestamp.encode(toTimestamp(message.scheduledDeparture), writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Trip {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTrip();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tripId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.driverId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.routeId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.stationAreaId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.destinationAreaId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.riderIds.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.scheduledDeparture = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Trip {
    return {
      tripId: isSet(object.tripId) ? globalThis.String(object.tripId) : "",
      driverId: isSet(object.driverId) ? globalThis.String(object.driverId) : "",
      routeId: isSet(object.routeId) ? globalThis.String(object.routeId) : "",
      stationAreaId: isSet(object.stationAreaId) ? globalThis.String(object.stationAreaId) : "",
      destinationAreaId: isSet(object.destinationAreaId) ? globalThis.String(object.destinationAreaId) : "",
      riderIds: globalThis.Array.isArray(object?.riderIds) ? object.riderIds.map((e: any) => globalThis.String(e)) : [],
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      scheduledDeparture: isSet(object.scheduledDeparture) ? fromJsonTimestamp(object.scheduledDeparture) : undefined,
    };
  },

  toJSON(message: Trip): unknown {
    const obj: any = {};
    if (message.tripId !== "") {
      obj.tripId = message.tripId;
    }
    if (message.driverId !== "") {
      obj.driverId = message.driverId;
    }
    if (message.routeId !== "") {
      obj.routeId = message.routeId;
    }
    if (message.stationAreaId !== "") {
      obj.stationAreaId = message.stationAreaId;
    }
    if (message.destinationAreaId !== "") {
      obj.destinationAreaId = message.destinationAreaId;
    }
    if (message.riderIds?.length) {
      obj.riderIds = message.riderIds;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.scheduledDeparture !== undefined) {
      obj.scheduledDeparture = message.scheduledDeparture.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Trip>, I>>(base?: I): Trip {
    return Trip.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Trip>, I>>(object: I): Trip {
    const message = createBaseTrip();
    message.tripId = object.tripId ?? "";
    message.driverId = object.driverId ?? "";
    message.routeId = object.routeId ?? "";
    message.stationAreaId = object.stationAreaId ?? "";
    message.destinationAreaId = object.destinationAreaId ?? "";
    message.riderIds = object.riderIds?.map((e) => e) || [];
    message.status = object.status ?? "";
    message.scheduledDeparture = object.scheduledDeparture ?? undefined;
    return message;
  },
};

function createBaseUpdateTripRequest(): UpdateTripRequest {
  return { tripId: "", status: "" };
}

export const UpdateTripRequest: MessageFns<UpdateTripRequest> = {
  encode(message: UpdateTripRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tripId !== "") {
      writer.uint32(10).string(message.tripId);
    }
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateTripRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateTripRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tripId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateTripRequest {
    return {
      tripId: isSet(object.tripId) ? globalThis.String(object.tripId) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
    };
  },

  toJSON(message: UpdateTripRequest): unknown {
    const obj: any = {};
    if (message.tripId !== "") {
      obj.tripId = message.tripId;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateTripRequest>, I>>(base?: I): UpdateTripRequest {
    return UpdateTripRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateTripRequest>, I>>(object: I): UpdateTripRequest {
    const message = createBaseUpdateTripRequest();
    message.tripId = object.tripId ?? "";
    message.status = object.status ?? "";
    return message;
  },
};

function createBaseTripId(): TripId {
  return { id: "" };
}

export const TripId: MessageFns<TripId> = {
  encode(message: TripId, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TripId {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTripId();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TripId {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: TripId): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TripId>, I>>(base?: I): TripId {
    return TripId.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TripId>, I>>(object: I): TripId {
    const message = createBaseTripId();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseGetTripsRequest(): GetTripsRequest {
  return { driverId: "", riderId: "" };
}

export const GetTripsRequest: MessageFns<GetTripsRequest> = {
  encode(message: GetTripsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.driverId !== "") {
      writer.uint32(10).string(message.driverId);
    }
    if (message.riderId !== "") {
      writer.uint32(18).string(message.riderId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTripsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTripsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.driverId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.riderId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTripsRequest {
    return {
      driverId: isSet(object.driverId) ? globalThis.String(object.driverId) : "",
      riderId: isSet(object.riderId) ? globalThis.String(object.riderId) : "",
    };
  },

  toJSON(message: GetTripsRequest): unknown {
    const obj: any = {};
    if (message.driverId !== "") {
      obj.driverId = message.driverId;
    }
    if (message.riderId !== "") {
      obj.riderId = message.riderId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTripsRequest>, I>>(base?: I): GetTripsRequest {
    return GetTripsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTripsRequest>, I>>(object: I): GetTripsRequest {
    const message = createBaseGetTripsRequest();
    message.driverId = object.driverId ?? "";
    message.riderId = object.riderId ?? "";
    return message;
  },
};

function createBaseGetTripsResponse(): GetTripsResponse {
  return { trips: [] };
}

export const GetTripsResponse: MessageFns<GetTripsResponse> = {
  encode(message: GetTripsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.trips) {
      Trip.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTripsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTripsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.trips.push(Trip.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTripsResponse {
    return { trips: globalThis.Array.isArray(object?.trips) ? object.trips.map((e: any) => Trip.fromJSON(e)) : [] };
  },

  toJSON(message: GetTripsResponse): unknown {
    const obj: any = {};
    if (message.trips?.length) {
      obj.trips = message.trips.map((e) => Trip.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTripsResponse>, I>>(base?: I): GetTripsResponse {
    return GetTripsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTripsResponse>, I>>(object: I): GetTripsResponse {
    const message = createBaseGetTripsResponse();
    message.trips = object.trips?.map((e) => Trip.fromPartial(e)) || [];
    return message;
  },
};

export interface TripService {
  CreateTrip(request: CreateTripRequest): Promise<Trip>;
  UpdateTripStatus(request: UpdateTripRequest): Promise<Trip>;
  GetTrip(request: TripId): Promise<Trip>;
  GetTrips(request: GetTripsRequest): Promise<GetTripsResponse>;
}

export const TripServiceServiceName = "lastmile.trip.TripService";
export class TripServiceClientImpl implements TripService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || TripServiceServiceName;
    this.rpc = rpc;
    this.CreateTrip = this.CreateTrip.bind(this);
    this.UpdateTripStatus = this.UpdateTripStatus.bind(this);
    this.GetTrip = this.GetTrip.bind(this);
    this.GetTrips = this.GetTrips.bind(this);
  }
  CreateTrip(request: CreateTripRequest): Promise<Trip> {
    const data = CreateTripRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateTrip", data);
    return promise.then((data) => Trip.decode(new BinaryReader(data)));
  }

  UpdateTripStatus(request: UpdateTripRequest): Promise<Trip> {
    const data = UpdateTripRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateTripStatus", data);
    return promise.then((data) => Trip.decode(new BinaryReader(data)));
  }

  GetTrip(request: TripId): Promise<Trip> {
    const data = TripId.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetTrip", data);
    return promise.then((data) => Trip.decode(new BinaryReader(data)));
  }

  GetTrips(request: GetTripsRequest): Promise<GetTripsResponse> {
    const data = GetTripsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetTrips", data);
    return promise.then((data) => GetTripsResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
