// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "driver.proto" (package "lastmile.driver", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { DriverService } from "./driver";
import type { DriverId } from "./driver";
import type { Ack } from "./driver";
import type { UpdatePickupRequest } from "./driver";
import type { UpdateRouteRequest } from "./driver";
import type { RoutePlan } from "./driver";
import type { RegisterRouteRequest } from "./driver";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { DriverProfile } from "./driver";
import type { RegisterDriverRequest } from "./driver";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service lastmile.driver.DriverService
 */
export interface IDriverServiceClient {
    /**
     * @generated from protobuf rpc: RegisterDriver
     */
    registerDriver(input: RegisterDriverRequest, options?: RpcOptions): UnaryCall<RegisterDriverRequest, DriverProfile>;
    /**
     * @generated from protobuf rpc: RegisterRoute
     */
    registerRoute(input: RegisterRouteRequest, options?: RpcOptions): UnaryCall<RegisterRouteRequest, RoutePlan>;
    /**
     * @generated from protobuf rpc: UpdateRoute
     */
    updateRoute(input: UpdateRouteRequest, options?: RpcOptions): UnaryCall<UpdateRouteRequest, RoutePlan>;
    /**
     * @generated from protobuf rpc: UpdatePickupStatus
     */
    updatePickupStatus(input: UpdatePickupRequest, options?: RpcOptions): UnaryCall<UpdatePickupRequest, Ack>;
    /**
     * @generated from protobuf rpc: GetDriver
     */
    getDriver(input: DriverId, options?: RpcOptions): UnaryCall<DriverId, DriverProfile>;
}
/**
 * @generated from protobuf service lastmile.driver.DriverService
 */
export class DriverServiceClient implements IDriverServiceClient, ServiceInfo {
    typeName = DriverService.typeName;
    methods = DriverService.methods;
    options = DriverService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: RegisterDriver
     */
    registerDriver(input: RegisterDriverRequest, options?: RpcOptions): UnaryCall<RegisterDriverRequest, DriverProfile> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterDriverRequest, DriverProfile>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RegisterRoute
     */
    registerRoute(input: RegisterRouteRequest, options?: RpcOptions): UnaryCall<RegisterRouteRequest, RoutePlan> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterRouteRequest, RoutePlan>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateRoute
     */
    updateRoute(input: UpdateRouteRequest, options?: RpcOptions): UnaryCall<UpdateRouteRequest, RoutePlan> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateRouteRequest, RoutePlan>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdatePickupStatus
     */
    updatePickupStatus(input: UpdatePickupRequest, options?: RpcOptions): UnaryCall<UpdatePickupRequest, Ack> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdatePickupRequest, Ack>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetDriver
     */
    getDriver(input: DriverId, options?: RpcOptions): UnaryCall<DriverId, DriverProfile> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<DriverId, DriverProfile>("unary", this._transport, method, opt, input);
    }
}
