// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "location.proto" (package "lastmile.location", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { LocationService } from "./location";
import type { DriverEta } from "./location";
import type { DriverEtaRequest } from "./location";
import type { DriverSnapshot } from "./location";
import type { DriverId } from "./location";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Ack } from "./location";
import type { DriverTelemetry } from "./location";
import type { ClientStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service lastmile.location.LocationService
 */
export interface ILocationServiceClient {
    /**
     * @generated from protobuf rpc: StreamDriverTelemetry
     */
    streamDriverTelemetry(options?: RpcOptions): ClientStreamingCall<DriverTelemetry, Ack>;
    /**
     * @generated from protobuf rpc: UpdateDriverLocation
     */
    updateDriverLocation(input: DriverTelemetry, options?: RpcOptions): UnaryCall<DriverTelemetry, Ack>;
    /**
     * @generated from protobuf rpc: GetDriverSnapshot
     */
    getDriverSnapshot(input: DriverId, options?: RpcOptions): UnaryCall<DriverId, DriverSnapshot>;
    /**
     * @generated from protobuf rpc: GetDriverEta
     */
    getDriverEta(input: DriverEtaRequest, options?: RpcOptions): UnaryCall<DriverEtaRequest, DriverEta>;
}
/**
 * @generated from protobuf service lastmile.location.LocationService
 */
export class LocationServiceClient implements ILocationServiceClient, ServiceInfo {
    typeName = LocationService.typeName;
    methods = LocationService.methods;
    options = LocationService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: StreamDriverTelemetry
     */
    streamDriverTelemetry(options?: RpcOptions): ClientStreamingCall<DriverTelemetry, Ack> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<DriverTelemetry, Ack>("clientStreaming", this._transport, method, opt);
    }
    /**
     * @generated from protobuf rpc: UpdateDriverLocation
     */
    updateDriverLocation(input: DriverTelemetry, options?: RpcOptions): UnaryCall<DriverTelemetry, Ack> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<DriverTelemetry, Ack>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetDriverSnapshot
     */
    getDriverSnapshot(input: DriverId, options?: RpcOptions): UnaryCall<DriverId, DriverSnapshot> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DriverId, DriverSnapshot>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetDriverEta
     */
    getDriverEta(input: DriverEtaRequest, options?: RpcOptions): UnaryCall<DriverEtaRequest, DriverEta> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<DriverEtaRequest, DriverEta>("unary", this._transport, method, opt, input);
    }
}
