// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "matching.proto" (package "lastmile.matching", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "./google/protobuf/timestamp";
/**
 * @generated from protobuf message lastmile.matching.EvaluateDriverRequest
 */
export interface EvaluateDriverRequest {
    /**
     * @generated from protobuf field: string driver_id = 1
     */
    driverId: string;
    /**
     * @generated from protobuf field: string route_id = 2
     */
    routeId: string;
    /**
     * @generated from protobuf field: string station_area_id = 3
     */
    stationAreaId: string;
    /**
     * @generated from protobuf field: string driver_current_area_id = 4
     */
    driverCurrentAreaId: string;
    /**
     * @generated from protobuf field: string destination_area_id = 5
     */
    destinationAreaId: string;
    /**
     * @generated from protobuf field: int32 seats_available = 6
     */
    seatsAvailable: number;
    /**
     * @generated from protobuf field: int32 eta_to_station_minutes = 7
     */
    etaToStationMinutes: number;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp driver_last_update = 8
     */
    driverLastUpdate?: Timestamp;
}
/**
 * @generated from protobuf message lastmile.matching.MatchResult
 */
export interface MatchResult {
    /**
     * @generated from protobuf field: string trip_id = 1
     */
    tripId: string;
    /**
     * @generated from protobuf field: string driver_id = 2
     */
    driverId: string;
    /**
     * @generated from protobuf field: string station_area_id = 3
     */
    stationAreaId: string;
    /**
     * @generated from protobuf field: string destination_area_id = 4
     */
    destinationAreaId: string;
    /**
     * @generated from protobuf field: repeated string rider_ids = 5
     */
    riderIds: string[];
}
/**
 * @generated from protobuf message lastmile.matching.MatchResponse
 */
export interface MatchResponse {
    /**
     * @generated from protobuf field: bool matched = 1
     */
    matched: boolean;
    /**
     * @generated from protobuf field: repeated lastmile.matching.MatchResult results = 2
     */
    results: MatchResult[];
    /**
     * @generated from protobuf field: string msg = 3
     */
    msg: string;
}
/**
 * @generated from protobuf message lastmile.matching.MatchEvent
 */
export interface MatchEvent {
    /**
     * @generated from protobuf field: string event_id = 1
     */
    eventId: string;
    /**
     * @generated from protobuf field: string station_area_id = 2
     */
    stationAreaId: string;
    /**
     * @generated from protobuf field: lastmile.matching.MatchResult result = 3
     */
    result?: MatchResult;
}
/**
 * @generated from protobuf message lastmile.matching.SubscribeRequest
 */
export interface SubscribeRequest {
    /**
     * @generated from protobuf field: string client_id = 1
     */
    clientId: string;
}
/**
 * @generated from protobuf message lastmile.matching.AddRiderIntentRequest
 */
export interface AddRiderIntentRequest {
    /**
     * @generated from protobuf field: string rider_id = 1
     */
    riderId: string;
    /**
     * @generated from protobuf field: string station_area_id = 2
     */
    stationAreaId: string;
    /**
     * @generated from protobuf field: string destination_area_id = 3
     */
    destinationAreaId: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp arrival_time = 4
     */
    arrivalTime?: Timestamp;
}
/**
 * @generated from protobuf message lastmile.matching.AddRiderIntentResponse
 */
export interface AddRiderIntentResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string msg = 2
     */
    msg: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class EvaluateDriverRequest$Type extends MessageType<EvaluateDriverRequest> {
    constructor() {
        super("lastmile.matching.EvaluateDriverRequest", [
            { no: 1, name: "driver_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "route_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "station_area_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "driver_current_area_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "destination_area_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "seats_available", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "eta_to_station_minutes", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "driver_last_update", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<EvaluateDriverRequest>): EvaluateDriverRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.driverId = "";
        message.routeId = "";
        message.stationAreaId = "";
        message.driverCurrentAreaId = "";
        message.destinationAreaId = "";
        message.seatsAvailable = 0;
        message.etaToStationMinutes = 0;
        if (value !== undefined)
            reflectionMergePartial<EvaluateDriverRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EvaluateDriverRequest): EvaluateDriverRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string driver_id */ 1:
                    message.driverId = reader.string();
                    break;
                case /* string route_id */ 2:
                    message.routeId = reader.string();
                    break;
                case /* string station_area_id */ 3:
                    message.stationAreaId = reader.string();
                    break;
                case /* string driver_current_area_id */ 4:
                    message.driverCurrentAreaId = reader.string();
                    break;
                case /* string destination_area_id */ 5:
                    message.destinationAreaId = reader.string();
                    break;
                case /* int32 seats_available */ 6:
                    message.seatsAvailable = reader.int32();
                    break;
                case /* int32 eta_to_station_minutes */ 7:
                    message.etaToStationMinutes = reader.int32();
                    break;
                case /* google.protobuf.Timestamp driver_last_update */ 8:
                    message.driverLastUpdate = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.driverLastUpdate);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EvaluateDriverRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string driver_id = 1; */
        if (message.driverId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.driverId);
        /* string route_id = 2; */
        if (message.routeId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.routeId);
        /* string station_area_id = 3; */
        if (message.stationAreaId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.stationAreaId);
        /* string driver_current_area_id = 4; */
        if (message.driverCurrentAreaId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.driverCurrentAreaId);
        /* string destination_area_id = 5; */
        if (message.destinationAreaId !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.destinationAreaId);
        /* int32 seats_available = 6; */
        if (message.seatsAvailable !== 0)
            writer.tag(6, WireType.Varint).int32(message.seatsAvailable);
        /* int32 eta_to_station_minutes = 7; */
        if (message.etaToStationMinutes !== 0)
            writer.tag(7, WireType.Varint).int32(message.etaToStationMinutes);
        /* google.protobuf.Timestamp driver_last_update = 8; */
        if (message.driverLastUpdate)
            Timestamp.internalBinaryWrite(message.driverLastUpdate, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lastmile.matching.EvaluateDriverRequest
 */
export const EvaluateDriverRequest = new EvaluateDriverRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MatchResult$Type extends MessageType<MatchResult> {
    constructor() {
        super("lastmile.matching.MatchResult", [
            { no: 1, name: "trip_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "driver_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "station_area_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "destination_area_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "rider_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<MatchResult>): MatchResult {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tripId = "";
        message.driverId = "";
        message.stationAreaId = "";
        message.destinationAreaId = "";
        message.riderIds = [];
        if (value !== undefined)
            reflectionMergePartial<MatchResult>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MatchResult): MatchResult {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string trip_id */ 1:
                    message.tripId = reader.string();
                    break;
                case /* string driver_id */ 2:
                    message.driverId = reader.string();
                    break;
                case /* string station_area_id */ 3:
                    message.stationAreaId = reader.string();
                    break;
                case /* string destination_area_id */ 4:
                    message.destinationAreaId = reader.string();
                    break;
                case /* repeated string rider_ids */ 5:
                    message.riderIds.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MatchResult, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string trip_id = 1; */
        if (message.tripId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.tripId);
        /* string driver_id = 2; */
        if (message.driverId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.driverId);
        /* string station_area_id = 3; */
        if (message.stationAreaId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.stationAreaId);
        /* string destination_area_id = 4; */
        if (message.destinationAreaId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.destinationAreaId);
        /* repeated string rider_ids = 5; */
        for (let i = 0; i < message.riderIds.length; i++)
            writer.tag(5, WireType.LengthDelimited).string(message.riderIds[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lastmile.matching.MatchResult
 */
export const MatchResult = new MatchResult$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MatchResponse$Type extends MessageType<MatchResponse> {
    constructor() {
        super("lastmile.matching.MatchResponse", [
            { no: 1, name: "matched", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "results", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => MatchResult },
            { no: 3, name: "msg", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<MatchResponse>): MatchResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.matched = false;
        message.results = [];
        message.msg = "";
        if (value !== undefined)
            reflectionMergePartial<MatchResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MatchResponse): MatchResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool matched */ 1:
                    message.matched = reader.bool();
                    break;
                case /* repeated lastmile.matching.MatchResult results */ 2:
                    message.results.push(MatchResult.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string msg */ 3:
                    message.msg = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MatchResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool matched = 1; */
        if (message.matched !== false)
            writer.tag(1, WireType.Varint).bool(message.matched);
        /* repeated lastmile.matching.MatchResult results = 2; */
        for (let i = 0; i < message.results.length; i++)
            MatchResult.internalBinaryWrite(message.results[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* string msg = 3; */
        if (message.msg !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.msg);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lastmile.matching.MatchResponse
 */
export const MatchResponse = new MatchResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MatchEvent$Type extends MessageType<MatchEvent> {
    constructor() {
        super("lastmile.matching.MatchEvent", [
            { no: 1, name: "event_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "station_area_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "result", kind: "message", T: () => MatchResult }
        ]);
    }
    create(value?: PartialMessage<MatchEvent>): MatchEvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventId = "";
        message.stationAreaId = "";
        if (value !== undefined)
            reflectionMergePartial<MatchEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MatchEvent): MatchEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string event_id */ 1:
                    message.eventId = reader.string();
                    break;
                case /* string station_area_id */ 2:
                    message.stationAreaId = reader.string();
                    break;
                case /* lastmile.matching.MatchResult result */ 3:
                    message.result = MatchResult.internalBinaryRead(reader, reader.uint32(), options, message.result);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MatchEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string event_id = 1; */
        if (message.eventId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.eventId);
        /* string station_area_id = 2; */
        if (message.stationAreaId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.stationAreaId);
        /* lastmile.matching.MatchResult result = 3; */
        if (message.result)
            MatchResult.internalBinaryWrite(message.result, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lastmile.matching.MatchEvent
 */
export const MatchEvent = new MatchEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SubscribeRequest$Type extends MessageType<SubscribeRequest> {
    constructor() {
        super("lastmile.matching.SubscribeRequest", [
            { no: 1, name: "client_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SubscribeRequest>): SubscribeRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.clientId = "";
        if (value !== undefined)
            reflectionMergePartial<SubscribeRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SubscribeRequest): SubscribeRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string client_id */ 1:
                    message.clientId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SubscribeRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string client_id = 1; */
        if (message.clientId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.clientId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lastmile.matching.SubscribeRequest
 */
export const SubscribeRequest = new SubscribeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddRiderIntentRequest$Type extends MessageType<AddRiderIntentRequest> {
    constructor() {
        super("lastmile.matching.AddRiderIntentRequest", [
            { no: 1, name: "rider_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "station_area_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "destination_area_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "arrival_time", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<AddRiderIntentRequest>): AddRiderIntentRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.riderId = "";
        message.stationAreaId = "";
        message.destinationAreaId = "";
        if (value !== undefined)
            reflectionMergePartial<AddRiderIntentRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddRiderIntentRequest): AddRiderIntentRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string rider_id */ 1:
                    message.riderId = reader.string();
                    break;
                case /* string station_area_id */ 2:
                    message.stationAreaId = reader.string();
                    break;
                case /* string destination_area_id */ 3:
                    message.destinationAreaId = reader.string();
                    break;
                case /* google.protobuf.Timestamp arrival_time */ 4:
                    message.arrivalTime = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.arrivalTime);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddRiderIntentRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string rider_id = 1; */
        if (message.riderId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.riderId);
        /* string station_area_id = 2; */
        if (message.stationAreaId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.stationAreaId);
        /* string destination_area_id = 3; */
        if (message.destinationAreaId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.destinationAreaId);
        /* google.protobuf.Timestamp arrival_time = 4; */
        if (message.arrivalTime)
            Timestamp.internalBinaryWrite(message.arrivalTime, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lastmile.matching.AddRiderIntentRequest
 */
export const AddRiderIntentRequest = new AddRiderIntentRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddRiderIntentResponse$Type extends MessageType<AddRiderIntentResponse> {
    constructor() {
        super("lastmile.matching.AddRiderIntentResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "msg", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AddRiderIntentResponse>): AddRiderIntentResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.msg = "";
        if (value !== undefined)
            reflectionMergePartial<AddRiderIntentResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddRiderIntentResponse): AddRiderIntentResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string msg */ 2:
                    message.msg = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddRiderIntentResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string msg = 2; */
        if (message.msg !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.msg);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lastmile.matching.AddRiderIntentResponse
 */
export const AddRiderIntentResponse = new AddRiderIntentResponse$Type();
/**
 * @generated ServiceType for protobuf service lastmile.matching.MatchingService
 */
export const MatchingService = new ServiceType("lastmile.matching.MatchingService", [
    { name: "EvaluateDriver", options: {}, I: EvaluateDriverRequest, O: MatchResponse },
    { name: "SubscribeMatches", serverStreaming: true, options: {}, I: SubscribeRequest, O: MatchEvent },
    { name: "AddRiderIntent", options: {}, I: AddRiderIntentRequest, O: AddRiderIntentResponse }
]);
