// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "rider.proto" (package "lastmile.rider", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "./google/protobuf/timestamp";
/**
 * @generated from protobuf message lastmile.rider.RegisterRideIntentRequest
 */
export interface RegisterRideIntentRequest {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
    /**
     * @generated from protobuf field: string station_area_id = 2
     */
    stationAreaId: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp arrival_time = 3
     */
    arrivalTime?: Timestamp;
    /**
     * @generated from protobuf field: string destination_area_id = 4
     */
    destinationAreaId: string;
    /**
     * @generated from protobuf field: int32 party_size = 5
     */
    partySize: number;
}
/**
 * @generated from protobuf message lastmile.rider.RideIntentResponse
 */
export interface RideIntentResponse {
    /**
     * @generated from protobuf field: string intent_id = 1
     */
    intentId: string;
}
/**
 * @generated from protobuf message lastmile.rider.RideId
 */
export interface RideId {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
}
/**
 * @generated from protobuf message lastmile.rider.RideStatus
 */
export interface RideStatus {
    /**
     * @generated from protobuf field: string intent_id = 1
     */
    intentId: string;
    /**
     * @generated from protobuf field: lastmile.rider.RideStatus.Status status = 2
     */
    status: RideStatus_Status;
    /**
     * @generated from protobuf field: string trip_id = 3
     */
    tripId: string;
    /**
     * @generated from protobuf field: string destination_area_id = 4
     */
    destinationAreaId: string;
    /**
     * @generated from protobuf field: string station_area_id = 5
     */
    stationAreaId: string;
}
/**
 * @generated from protobuf enum lastmile.rider.RideStatus.Status
 */
export enum RideStatus_Status {
    /**
     * @generated from protobuf enum value: PENDING = 0;
     */
    PENDING = 0,
    /**
     * @generated from protobuf enum value: SCHEDULED = 1;
     */
    SCHEDULED = 1,
    /**
     * @generated from protobuf enum value: PICKED_UP = 2;
     */
    PICKED_UP = 2,
    /**
     * @generated from protobuf enum value: COMPLETED = 3;
     */
    COMPLETED = 3,
    /**
     * @generated from protobuf enum value: CANCELLED = 4;
     */
    CANCELLED = 4
}
/**
 * @generated from protobuf message lastmile.rider.GetRideHistoryRequest
 */
export interface GetRideHistoryRequest {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
}
/**
 * @generated from protobuf message lastmile.rider.RideHistoryResponse
 */
export interface RideHistoryResponse {
    /**
     * @generated from protobuf field: repeated lastmile.rider.RideStatus rides = 1
     */
    rides: RideStatus[];
}
// @generated message type with reflection information, may provide speed optimized methods
class RegisterRideIntentRequest$Type extends MessageType<RegisterRideIntentRequest> {
    constructor() {
        super("lastmile.rider.RegisterRideIntentRequest", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "station_area_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "arrival_time", kind: "message", T: () => Timestamp },
            { no: 4, name: "destination_area_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "party_size", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<RegisterRideIntentRequest>): RegisterRideIntentRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        message.stationAreaId = "";
        message.destinationAreaId = "";
        message.partySize = 0;
        if (value !== undefined)
            reflectionMergePartial<RegisterRideIntentRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterRideIntentRequest): RegisterRideIntentRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                case /* string station_area_id */ 2:
                    message.stationAreaId = reader.string();
                    break;
                case /* google.protobuf.Timestamp arrival_time */ 3:
                    message.arrivalTime = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.arrivalTime);
                    break;
                case /* string destination_area_id */ 4:
                    message.destinationAreaId = reader.string();
                    break;
                case /* int32 party_size */ 5:
                    message.partySize = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterRideIntentRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        /* string station_area_id = 2; */
        if (message.stationAreaId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.stationAreaId);
        /* google.protobuf.Timestamp arrival_time = 3; */
        if (message.arrivalTime)
            Timestamp.internalBinaryWrite(message.arrivalTime, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* string destination_area_id = 4; */
        if (message.destinationAreaId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.destinationAreaId);
        /* int32 party_size = 5; */
        if (message.partySize !== 0)
            writer.tag(5, WireType.Varint).int32(message.partySize);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lastmile.rider.RegisterRideIntentRequest
 */
export const RegisterRideIntentRequest = new RegisterRideIntentRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RideIntentResponse$Type extends MessageType<RideIntentResponse> {
    constructor() {
        super("lastmile.rider.RideIntentResponse", [
            { no: 1, name: "intent_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RideIntentResponse>): RideIntentResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.intentId = "";
        if (value !== undefined)
            reflectionMergePartial<RideIntentResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RideIntentResponse): RideIntentResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string intent_id */ 1:
                    message.intentId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RideIntentResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string intent_id = 1; */
        if (message.intentId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.intentId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lastmile.rider.RideIntentResponse
 */
export const RideIntentResponse = new RideIntentResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RideId$Type extends MessageType<RideId> {
    constructor() {
        super("lastmile.rider.RideId", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RideId>): RideId {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<RideId>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RideId): RideId {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RideId, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lastmile.rider.RideId
 */
export const RideId = new RideId$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RideStatus$Type extends MessageType<RideStatus> {
    constructor() {
        super("lastmile.rider.RideStatus", [
            { no: 1, name: "intent_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "status", kind: "enum", T: () => ["lastmile.rider.RideStatus.Status", RideStatus_Status] },
            { no: 3, name: "trip_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "destination_area_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "station_area_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RideStatus>): RideStatus {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.intentId = "";
        message.status = 0;
        message.tripId = "";
        message.destinationAreaId = "";
        message.stationAreaId = "";
        if (value !== undefined)
            reflectionMergePartial<RideStatus>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RideStatus): RideStatus {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string intent_id */ 1:
                    message.intentId = reader.string();
                    break;
                case /* lastmile.rider.RideStatus.Status status */ 2:
                    message.status = reader.int32();
                    break;
                case /* string trip_id */ 3:
                    message.tripId = reader.string();
                    break;
                case /* string destination_area_id */ 4:
                    message.destinationAreaId = reader.string();
                    break;
                case /* string station_area_id */ 5:
                    message.stationAreaId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RideStatus, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string intent_id = 1; */
        if (message.intentId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.intentId);
        /* lastmile.rider.RideStatus.Status status = 2; */
        if (message.status !== 0)
            writer.tag(2, WireType.Varint).int32(message.status);
        /* string trip_id = 3; */
        if (message.tripId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.tripId);
        /* string destination_area_id = 4; */
        if (message.destinationAreaId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.destinationAreaId);
        /* string station_area_id = 5; */
        if (message.stationAreaId !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.stationAreaId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lastmile.rider.RideStatus
 */
export const RideStatus = new RideStatus$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetRideHistoryRequest$Type extends MessageType<GetRideHistoryRequest> {
    constructor() {
        super("lastmile.rider.GetRideHistoryRequest", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetRideHistoryRequest>): GetRideHistoryRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        if (value !== undefined)
            reflectionMergePartial<GetRideHistoryRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetRideHistoryRequest): GetRideHistoryRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetRideHistoryRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lastmile.rider.GetRideHistoryRequest
 */
export const GetRideHistoryRequest = new GetRideHistoryRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RideHistoryResponse$Type extends MessageType<RideHistoryResponse> {
    constructor() {
        super("lastmile.rider.RideHistoryResponse", [
            { no: 1, name: "rides", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => RideStatus }
        ]);
    }
    create(value?: PartialMessage<RideHistoryResponse>): RideHistoryResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.rides = [];
        if (value !== undefined)
            reflectionMergePartial<RideHistoryResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RideHistoryResponse): RideHistoryResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated lastmile.rider.RideStatus rides */ 1:
                    message.rides.push(RideStatus.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RideHistoryResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated lastmile.rider.RideStatus rides = 1; */
        for (let i = 0; i < message.rides.length; i++)
            RideStatus.internalBinaryWrite(message.rides[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lastmile.rider.RideHistoryResponse
 */
export const RideHistoryResponse = new RideHistoryResponse$Type();
/**
 * @generated ServiceType for protobuf service lastmile.rider.RiderService
 */
export const RiderService = new ServiceType("lastmile.rider.RiderService", [
    { name: "RegisterRideIntent", options: {}, I: RegisterRideIntentRequest, O: RideIntentResponse },
    { name: "GetRideStatus", options: {}, I: RideId, O: RideStatus },
    { name: "GetRideHistory", options: {}, I: GetRideHistoryRequest, O: RideHistoryResponse }
]);
