// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "rider.proto" (package "lastmile.rider", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { RiderService } from "./rider";
import type { RideHistoryResponse } from "./rider";
import type { GetRideHistoryRequest } from "./rider";
import type { RideStatus } from "./rider";
import type { RideId } from "./rider";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { RideIntentResponse } from "./rider";
import type { RegisterRideIntentRequest } from "./rider";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service lastmile.rider.RiderService
 */
export interface IRiderServiceClient {
    /**
     * @generated from protobuf rpc: RegisterRideIntent
     */
    registerRideIntent(input: RegisterRideIntentRequest, options?: RpcOptions): UnaryCall<RegisterRideIntentRequest, RideIntentResponse>;
    /**
     * @generated from protobuf rpc: GetRideStatus
     */
    getRideStatus(input: RideId, options?: RpcOptions): UnaryCall<RideId, RideStatus>;
    /**
     * @generated from protobuf rpc: GetRideHistory
     */
    getRideHistory(input: GetRideHistoryRequest, options?: RpcOptions): UnaryCall<GetRideHistoryRequest, RideHistoryResponse>;
}
/**
 * @generated from protobuf service lastmile.rider.RiderService
 */
export class RiderServiceClient implements IRiderServiceClient, ServiceInfo {
    typeName = RiderService.typeName;
    methods = RiderService.methods;
    options = RiderService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: RegisterRideIntent
     */
    registerRideIntent(input: RegisterRideIntentRequest, options?: RpcOptions): UnaryCall<RegisterRideIntentRequest, RideIntentResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<RegisterRideIntentRequest, RideIntentResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetRideStatus
     */
    getRideStatus(input: RideId, options?: RpcOptions): UnaryCall<RideId, RideStatus> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<RideId, RideStatus>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetRideHistory
     */
    getRideHistory(input: GetRideHistoryRequest, options?: RpcOptions): UnaryCall<GetRideHistoryRequest, RideHistoryResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetRideHistoryRequest, RideHistoryResponse>("unary", this._transport, method, opt, input);
    }
}
