// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "station.proto" (package "lastmile.station", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { StationService } from "./station";
import type { ListStationsRequest } from "./station";
import type { AreaList } from "./station";
import type { ListAreasRequest } from "./station";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Area } from "./common";
import type { AreaId } from "./station";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service lastmile.station.StationService
 */
export interface IStationServiceClient {
    /**
     * @generated from protobuf rpc: GetArea
     */
    getArea(input: AreaId, options?: RpcOptions): UnaryCall<AreaId, Area>;
    /**
     * @generated from protobuf rpc: ListAreas
     */
    listAreas(input: ListAreasRequest, options?: RpcOptions): UnaryCall<ListAreasRequest, AreaList>;
    /**
     * @generated from protobuf rpc: ListStations
     */
    listStations(input: ListStationsRequest, options?: RpcOptions): UnaryCall<ListStationsRequest, AreaList>;
}
/**
 * @generated from protobuf service lastmile.station.StationService
 */
export class StationServiceClient implements IStationServiceClient, ServiceInfo {
    typeName = StationService.typeName;
    methods = StationService.methods;
    options = StationService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetArea
     */
    getArea(input: AreaId, options?: RpcOptions): UnaryCall<AreaId, Area> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<AreaId, Area>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListAreas
     */
    listAreas(input: ListAreasRequest, options?: RpcOptions): UnaryCall<ListAreasRequest, AreaList> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAreasRequest, AreaList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListStations
     */
    listStations(input: ListStationsRequest, options?: RpcOptions): UnaryCall<ListStationsRequest, AreaList> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListStationsRequest, AreaList>("unary", this._transport, method, opt, input);
    }
}
