// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "trip.proto" (package "lastmile.trip", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "./google/protobuf/timestamp";
/**
 * @generated from protobuf message lastmile.trip.CreateTripRequest
 */
export interface CreateTripRequest {
    /**
     * @generated from protobuf field: string driver_id = 1
     */
    driverId: string;
    /**
     * @generated from protobuf field: string route_id = 2
     */
    routeId: string;
    /**
     * @generated from protobuf field: string station_area_id = 3
     */
    stationAreaId: string;
    /**
     * @generated from protobuf field: repeated string rider_ids = 4
     */
    riderIds: string[];
    /**
     * @generated from protobuf field: string destination_area_id = 5
     */
    destinationAreaId: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp scheduled_departure = 6
     */
    scheduledDeparture?: Timestamp;
}
/**
 * @generated from protobuf message lastmile.trip.Trip
 */
export interface Trip {
    /**
     * @generated from protobuf field: string trip_id = 1
     */
    tripId: string;
    /**
     * @generated from protobuf field: string driver_id = 2
     */
    driverId: string;
    /**
     * @generated from protobuf field: string route_id = 3
     */
    routeId: string;
    /**
     * @generated from protobuf field: string station_area_id = 4
     */
    stationAreaId: string;
    /**
     * @generated from protobuf field: string destination_area_id = 5
     */
    destinationAreaId: string;
    /**
     * @generated from protobuf field: repeated string rider_ids = 6
     */
    riderIds: string[];
    /**
     * @generated from protobuf field: string status = 7
     */
    status: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp scheduled_departure = 8
     */
    scheduledDeparture?: Timestamp;
}
/**
 * @generated from protobuf message lastmile.trip.UpdateTripRequest
 */
export interface UpdateTripRequest {
    /**
     * @generated from protobuf field: string trip_id = 1
     */
    tripId: string;
    /**
     * @generated from protobuf field: string status = 2
     */
    status: string;
}
/**
 * @generated from protobuf message lastmile.trip.TripId
 */
export interface TripId {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
}
/**
 * @generated from protobuf message lastmile.trip.GetTripsRequest
 */
export interface GetTripsRequest {
    /**
     * @generated from protobuf field: string driver_id = 1
     */
    driverId: string;
    /**
     * @generated from protobuf field: string rider_id = 2
     */
    riderId: string;
}
/**
 * @generated from protobuf message lastmile.trip.GetTripsResponse
 */
export interface GetTripsResponse {
    /**
     * @generated from protobuf field: repeated lastmile.trip.Trip trips = 1
     */
    trips: Trip[];
}
// @generated message type with reflection information, may provide speed optimized methods
class CreateTripRequest$Type extends MessageType<CreateTripRequest> {
    constructor() {
        super("lastmile.trip.CreateTripRequest", [
            { no: 1, name: "driver_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "route_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "station_area_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "rider_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "destination_area_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "scheduled_departure", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<CreateTripRequest>): CreateTripRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.driverId = "";
        message.routeId = "";
        message.stationAreaId = "";
        message.riderIds = [];
        message.destinationAreaId = "";
        if (value !== undefined)
            reflectionMergePartial<CreateTripRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateTripRequest): CreateTripRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string driver_id */ 1:
                    message.driverId = reader.string();
                    break;
                case /* string route_id */ 2:
                    message.routeId = reader.string();
                    break;
                case /* string station_area_id */ 3:
                    message.stationAreaId = reader.string();
                    break;
                case /* repeated string rider_ids */ 4:
                    message.riderIds.push(reader.string());
                    break;
                case /* string destination_area_id */ 5:
                    message.destinationAreaId = reader.string();
                    break;
                case /* google.protobuf.Timestamp scheduled_departure */ 6:
                    message.scheduledDeparture = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.scheduledDeparture);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateTripRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string driver_id = 1; */
        if (message.driverId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.driverId);
        /* string route_id = 2; */
        if (message.routeId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.routeId);
        /* string station_area_id = 3; */
        if (message.stationAreaId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.stationAreaId);
        /* repeated string rider_ids = 4; */
        for (let i = 0; i < message.riderIds.length; i++)
            writer.tag(4, WireType.LengthDelimited).string(message.riderIds[i]);
        /* string destination_area_id = 5; */
        if (message.destinationAreaId !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.destinationAreaId);
        /* google.protobuf.Timestamp scheduled_departure = 6; */
        if (message.scheduledDeparture)
            Timestamp.internalBinaryWrite(message.scheduledDeparture, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lastmile.trip.CreateTripRequest
 */
export const CreateTripRequest = new CreateTripRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Trip$Type extends MessageType<Trip> {
    constructor() {
        super("lastmile.trip.Trip", [
            { no: 1, name: "trip_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "driver_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "route_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "station_area_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "destination_area_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "rider_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "scheduled_departure", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<Trip>): Trip {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tripId = "";
        message.driverId = "";
        message.routeId = "";
        message.stationAreaId = "";
        message.destinationAreaId = "";
        message.riderIds = [];
        message.status = "";
        if (value !== undefined)
            reflectionMergePartial<Trip>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Trip): Trip {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string trip_id */ 1:
                    message.tripId = reader.string();
                    break;
                case /* string driver_id */ 2:
                    message.driverId = reader.string();
                    break;
                case /* string route_id */ 3:
                    message.routeId = reader.string();
                    break;
                case /* string station_area_id */ 4:
                    message.stationAreaId = reader.string();
                    break;
                case /* string destination_area_id */ 5:
                    message.destinationAreaId = reader.string();
                    break;
                case /* repeated string rider_ids */ 6:
                    message.riderIds.push(reader.string());
                    break;
                case /* string status */ 7:
                    message.status = reader.string();
                    break;
                case /* google.protobuf.Timestamp scheduled_departure */ 8:
                    message.scheduledDeparture = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.scheduledDeparture);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Trip, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string trip_id = 1; */
        if (message.tripId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.tripId);
        /* string driver_id = 2; */
        if (message.driverId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.driverId);
        /* string route_id = 3; */
        if (message.routeId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.routeId);
        /* string station_area_id = 4; */
        if (message.stationAreaId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.stationAreaId);
        /* string destination_area_id = 5; */
        if (message.destinationAreaId !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.destinationAreaId);
        /* repeated string rider_ids = 6; */
        for (let i = 0; i < message.riderIds.length; i++)
            writer.tag(6, WireType.LengthDelimited).string(message.riderIds[i]);
        /* string status = 7; */
        if (message.status !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.status);
        /* google.protobuf.Timestamp scheduled_departure = 8; */
        if (message.scheduledDeparture)
            Timestamp.internalBinaryWrite(message.scheduledDeparture, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lastmile.trip.Trip
 */
export const Trip = new Trip$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateTripRequest$Type extends MessageType<UpdateTripRequest> {
    constructor() {
        super("lastmile.trip.UpdateTripRequest", [
            { no: 1, name: "trip_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UpdateTripRequest>): UpdateTripRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tripId = "";
        message.status = "";
        if (value !== undefined)
            reflectionMergePartial<UpdateTripRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateTripRequest): UpdateTripRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string trip_id */ 1:
                    message.tripId = reader.string();
                    break;
                case /* string status */ 2:
                    message.status = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateTripRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string trip_id = 1; */
        if (message.tripId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.tripId);
        /* string status = 2; */
        if (message.status !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lastmile.trip.UpdateTripRequest
 */
export const UpdateTripRequest = new UpdateTripRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TripId$Type extends MessageType<TripId> {
    constructor() {
        super("lastmile.trip.TripId", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<TripId>): TripId {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<TripId>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TripId): TripId {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TripId, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lastmile.trip.TripId
 */
export const TripId = new TripId$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetTripsRequest$Type extends MessageType<GetTripsRequest> {
    constructor() {
        super("lastmile.trip.GetTripsRequest", [
            { no: 1, name: "driver_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "rider_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetTripsRequest>): GetTripsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.driverId = "";
        message.riderId = "";
        if (value !== undefined)
            reflectionMergePartial<GetTripsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetTripsRequest): GetTripsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string driver_id */ 1:
                    message.driverId = reader.string();
                    break;
                case /* string rider_id */ 2:
                    message.riderId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetTripsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string driver_id = 1; */
        if (message.driverId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.driverId);
        /* string rider_id = 2; */
        if (message.riderId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.riderId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lastmile.trip.GetTripsRequest
 */
export const GetTripsRequest = new GetTripsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetTripsResponse$Type extends MessageType<GetTripsResponse> {
    constructor() {
        super("lastmile.trip.GetTripsResponse", [
            { no: 1, name: "trips", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Trip }
        ]);
    }
    create(value?: PartialMessage<GetTripsResponse>): GetTripsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.trips = [];
        if (value !== undefined)
            reflectionMergePartial<GetTripsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetTripsResponse): GetTripsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated lastmile.trip.Trip trips */ 1:
                    message.trips.push(Trip.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetTripsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated lastmile.trip.Trip trips = 1; */
        for (let i = 0; i < message.trips.length; i++)
            Trip.internalBinaryWrite(message.trips[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message lastmile.trip.GetTripsResponse
 */
export const GetTripsResponse = new GetTripsResponse$Type();
/**
 * @generated ServiceType for protobuf service lastmile.trip.TripService
 */
export const TripService = new ServiceType("lastmile.trip.TripService", [
    { name: "CreateTrip", options: {}, I: CreateTripRequest, O: Trip },
    { name: "UpdateTripStatus", options: {}, I: UpdateTripRequest, O: Trip },
    { name: "GetTrip", options: {}, I: TripId, O: Trip },
    { name: "GetTrips", options: {}, I: GetTripsRequest, O: GetTripsResponse }
]);
