// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "trip.proto" (package "lastmile.trip", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { TripService } from "./trip";
import type { GetTripsResponse } from "./trip";
import type { GetTripsRequest } from "./trip";
import type { TripId } from "./trip";
import type { UpdateTripRequest } from "./trip";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Trip } from "./trip";
import type { CreateTripRequest } from "./trip";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service lastmile.trip.TripService
 */
export interface ITripServiceClient {
    /**
     * @generated from protobuf rpc: CreateTrip
     */
    createTrip(input: CreateTripRequest, options?: RpcOptions): UnaryCall<CreateTripRequest, Trip>;
    /**
     * @generated from protobuf rpc: UpdateTripStatus
     */
    updateTripStatus(input: UpdateTripRequest, options?: RpcOptions): UnaryCall<UpdateTripRequest, Trip>;
    /**
     * @generated from protobuf rpc: GetTrip
     */
    getTrip(input: TripId, options?: RpcOptions): UnaryCall<TripId, Trip>;
    /**
     * @generated from protobuf rpc: GetTrips
     */
    getTrips(input: GetTripsRequest, options?: RpcOptions): UnaryCall<GetTripsRequest, GetTripsResponse>;
}
/**
 * @generated from protobuf service lastmile.trip.TripService
 */
export class TripServiceClient implements ITripServiceClient, ServiceInfo {
    typeName = TripService.typeName;
    methods = TripService.methods;
    options = TripService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateTrip
     */
    createTrip(input: CreateTripRequest, options?: RpcOptions): UnaryCall<CreateTripRequest, Trip> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateTripRequest, Trip>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateTripStatus
     */
    updateTripStatus(input: UpdateTripRequest, options?: RpcOptions): UnaryCall<UpdateTripRequest, Trip> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateTripRequest, Trip>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetTrip
     */
    getTrip(input: TripId, options?: RpcOptions): UnaryCall<TripId, Trip> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<TripId, Trip>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetTrips
     */
    getTrips(input: GetTripsRequest, options?: RpcOptions): UnaryCall<GetTripsRequest, GetTripsResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetTripsRequest, GetTripsResponse>("unary", this._transport, method, opt, input);
    }
}
