// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "user.proto" (package "lastmile.user", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { UserService } from "./user";
import type { UserProfile } from "./user";
import type { UserId } from "./common";
import type { AuthResponse } from "./user";
import type { Credentials } from "./user";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CreateUserResponse } from "./user";
import type { CreateUserRequest } from "./user";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service lastmile.user.UserService
 */
export interface IUserServiceClient {
    /**
     * @generated from protobuf rpc: CreateUser
     */
    createUser(input: CreateUserRequest, options?: RpcOptions): UnaryCall<CreateUserRequest, CreateUserResponse>;
    /**
     * @generated from protobuf rpc: Authenticate
     */
    authenticate(input: Credentials, options?: RpcOptions): UnaryCall<Credentials, AuthResponse>;
    /**
     * @generated from protobuf rpc: GetUser
     */
    getUser(input: UserId, options?: RpcOptions): UnaryCall<UserId, UserProfile>;
}
/**
 * @generated from protobuf service lastmile.user.UserService
 */
export class UserServiceClient implements IUserServiceClient, ServiceInfo {
    typeName = UserService.typeName;
    methods = UserService.methods;
    options = UserService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateUser
     */
    createUser(input: CreateUserRequest, options?: RpcOptions): UnaryCall<CreateUserRequest, CreateUserResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateUserRequest, CreateUserResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Authenticate
     */
    authenticate(input: Credentials, options?: RpcOptions): UnaryCall<Credentials, AuthResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<Credentials, AuthResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetUser
     */
    getUser(input: UserId, options?: RpcOptions): UnaryCall<UserId, UserProfile> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<UserId, UserProfile>("unary", this._transport, method, opt, input);
    }
}
