import { Injectable } from '@angular/core';
import { UserServiceClientImpl, Credentials, AuthResponse, CreateUserRequest, CreateUserResponse, UserProfile } from '../../../proto/user';
import { UserId } from '../../../proto/common';
import { BehaviorSubject, Observable, from } from 'rxjs';
import { map, tap } from 'rxjs/operators';
import { GrpcWebRpc } from '../grpc/grpc-web-rpc';
import { GRPC_URL } from '../grpc/grpc-clients.module';

@Injectable({
    providedIn: 'root'
})
export class AuthService {
    private readonly TOKEN_KEY = 'auth_token';
    private readonly USER_ID_KEY = 'user_id';
    private readonly ROLE_KEY = 'user_role';

    private isAuthenticatedSubject = new BehaviorSubject<boolean>(this.hasToken());
    public isAuthenticated$ = this.isAuthenticatedSubject.asObservable();

    private userServiceClient: UserServiceClientImpl;

    constructor() {
        const rpc = new GrpcWebRpc(GRPC_URL);
        this.userServiceClient = new UserServiceClientImpl(rpc);
    }

    private hasToken(): boolean {
        return !!localStorage.getItem(this.TOKEN_KEY);
    }

    getToken(): string | null {
        return localStorage.getItem(this.TOKEN_KEY);
    }

    getUserId(): string | null {
        return localStorage.getItem(this.USER_ID_KEY);
    }

    getUserRole(): string | null {
        return localStorage.getItem(this.ROLE_KEY);
    }

    getMetadata(): { [key: string]: string } {
        const token = this.getToken();
        const metadata: { [key: string]: string } = {};
        if (token) {
            metadata['Authorization'] = `Bearer ${token}`;
        }
        return metadata;
    }

    getUserProfile(): Observable<UserProfile> {
        const userIdStr = this.getUserId();
        if (!userIdStr) throw new Error('User ID not found');

        const req: UserId = { id: userIdStr };

        // Note: Metadata handling needs to be passed to Rpc if supported, 
        // but generic Rpc interface in user.ts doesn't accept metadata in request() method signature?
        // Let's check user.ts Rpc interface again.
        // It says: request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
        // So we can't pass metadata easily with this generic interface unless we modify it or the adapter.
        // For now, we'll skip metadata or bake it into the adapter if needed.
        // Actually, we can update GrpcWebRpc to take metadata in constructor or method if we change the interface?
        // But the interface is generated by ts-proto.

        return from(this.userServiceClient.GetUser(req));
    }

    login(email: string, password: string): Observable<AuthResponse> {
        const req: Credentials = { email, password };

        return from(this.userServiceClient.Authenticate(req)).pipe(
            tap(res => {
                if (!res.jwt || res.jwt === 'INVALID') {
                    throw new Error('Invalid credentials');
                }
                localStorage.setItem(this.TOKEN_KEY, res.jwt);
                this.isAuthenticatedSubject.next(true);
                this.decodeToken(res.jwt);
            })
        );
    }

    signup(req: CreateUserRequest): Observable<CreateUserResponse> {
        return from(this.userServiceClient.CreateUser(req));
    }

    logout() {
        localStorage.removeItem(this.TOKEN_KEY);
        localStorage.removeItem(this.USER_ID_KEY);
        localStorage.removeItem(this.ROLE_KEY);
        this.isAuthenticatedSubject.next(false);
    }

    private decodeToken(token: string) {
        if (!token || token.split('.').length < 2) {
            return;
        }
        try {
            const base64Url = token.split('.')[1];
            const base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
            const jsonPayload = decodeURIComponent(atob(base64).split('').map(function (c) {
                return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
            }).join(''));

            const payload = JSON.parse(jsonPayload);
            if (payload.sub) {
                localStorage.setItem(this.USER_ID_KEY, payload.sub);
            }
            if (payload.role) {
                localStorage.setItem(this.ROLE_KEY, payload.role);
            }
        } catch (e) {
            console.error('Failed to decode token', e);
        }
    }
}
